// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom
{
    public static class GetIntegrationCentricProfile
    {
        /// <summary>
        /// An Integration Centric Profile defines the Remote Server integrations a user is expected to add and connect during integration-centric onboarding.
        /// 
        /// 
        /// 
        /// Use this to automate setup guidance for users who need access to multiple business systems without sending long manual instructions. Common scenarios include ongoing access to systems such as SharePoint, bridging Google, Microsoft, and Box environments after M&amp;A activity, and migrations where users connect legacy EFSS accounts during transition work.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const exampleIntegrationCentricProfile = filescom.getIntegrationCentricProfile({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_integration_centric_profile = filescom.get_integration_centric_profile(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleIntegrationCentricProfile = Filescom.GetIntegrationCentricProfile.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetIntegrationCentricProfile(ctx, &amp;filescom.LookupIntegrationCentricProfileArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getintegrationcentricprofile" "exampleIntegrationCentricProfile" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetIntegrationCentricProfileArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var exampleIntegrationCentricProfile = FilescomFunctions.getIntegrationCentricProfile(GetIntegrationCentricProfileArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   exampleIntegrationCentricProfile:
        ///     fn::invoke:
        ///       function: filescom:getIntegrationCentricProfile
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Task<GetIntegrationCentricProfileResult> InvokeAsync(GetIntegrationCentricProfileArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetIntegrationCentricProfileResult>("filescom:index/getIntegrationCentricProfile:getIntegrationCentricProfile", args ?? new GetIntegrationCentricProfileArgs(), options.WithDefaults());

        /// <summary>
        /// An Integration Centric Profile defines the Remote Server integrations a user is expected to add and connect during integration-centric onboarding.
        /// 
        /// 
        /// 
        /// Use this to automate setup guidance for users who need access to multiple business systems without sending long manual instructions. Common scenarios include ongoing access to systems such as SharePoint, bridging Google, Microsoft, and Box environments after M&amp;A activity, and migrations where users connect legacy EFSS accounts during transition work.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const exampleIntegrationCentricProfile = filescom.getIntegrationCentricProfile({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_integration_centric_profile = filescom.get_integration_centric_profile(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleIntegrationCentricProfile = Filescom.GetIntegrationCentricProfile.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetIntegrationCentricProfile(ctx, &amp;filescom.LookupIntegrationCentricProfileArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getintegrationcentricprofile" "exampleIntegrationCentricProfile" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetIntegrationCentricProfileArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var exampleIntegrationCentricProfile = FilescomFunctions.getIntegrationCentricProfile(GetIntegrationCentricProfileArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   exampleIntegrationCentricProfile:
        ///     fn::invoke:
        ///       function: filescom:getIntegrationCentricProfile
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetIntegrationCentricProfileResult> Invoke(GetIntegrationCentricProfileInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetIntegrationCentricProfileResult>("filescom:index/getIntegrationCentricProfile:getIntegrationCentricProfile", args ?? new GetIntegrationCentricProfileInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// An Integration Centric Profile defines the Remote Server integrations a user is expected to add and connect during integration-centric onboarding.
        /// 
        /// 
        /// 
        /// Use this to automate setup guidance for users who need access to multiple business systems without sending long manual instructions. Common scenarios include ongoing access to systems such as SharePoint, bridging Google, Microsoft, and Box environments after M&amp;A activity, and migrations where users connect legacy EFSS accounts during transition work.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const exampleIntegrationCentricProfile = filescom.getIntegrationCentricProfile({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_integration_centric_profile = filescom.get_integration_centric_profile(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleIntegrationCentricProfile = Filescom.GetIntegrationCentricProfile.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetIntegrationCentricProfile(ctx, &amp;filescom.LookupIntegrationCentricProfileArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getintegrationcentricprofile" "exampleIntegrationCentricProfile" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetIntegrationCentricProfileArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var exampleIntegrationCentricProfile = FilescomFunctions.getIntegrationCentricProfile(GetIntegrationCentricProfileArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   exampleIntegrationCentricProfile:
        ///     fn::invoke:
        ///       function: filescom:getIntegrationCentricProfile
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetIntegrationCentricProfileResult> Invoke(GetIntegrationCentricProfileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetIntegrationCentricProfileResult>("filescom:index/getIntegrationCentricProfile:getIntegrationCentricProfile", args ?? new GetIntegrationCentricProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetIntegrationCentricProfileArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Integration Centric Profile ID
        /// </summary>
        [Input("id", required: true)]
        public int Id { get; set; }

        public GetIntegrationCentricProfileArgs()
        {
        }
        public static new GetIntegrationCentricProfileArgs Empty => new GetIntegrationCentricProfileArgs();
    }

    public sealed class GetIntegrationCentricProfileInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Integration Centric Profile ID
        /// </summary>
        [Input("id", required: true)]
        public Input<int> Id { get; set; } = null!;

        public GetIntegrationCentricProfileInvokeArgs()
        {
        }
        public static new GetIntegrationCentricProfileInvokeArgs Empty => new GetIntegrationCentricProfileInvokeArgs();
    }


    [OutputType]
    public sealed class GetIntegrationCentricProfileResult
    {
        /// <summary>
        /// Remote Server integrations the user is expected to add and connect. Each entry requires &lt;span pulumi-lang-nodejs="`serverType`" pulumi-lang-dotnet="`ServerType`" pulumi-lang-go="`serverType`" pulumi-lang-python="`server_type`" pulumi-lang-yaml="`serverType`" pulumi-lang-java="`serverType`" pulumi-lang-hcl="`server_type`"&gt;`serverType`&lt;/span&gt; and may include a display &lt;span pulumi-lang-nodejs="`name`" pulumi-lang-dotnet="`Name`" pulumi-lang-go="`name`" pulumi-lang-python="`name`" pulumi-lang-yaml="`name`" pulumi-lang-java="`name`" pulumi-lang-hcl="`name`"&gt;`name`&lt;/span&gt;.
        /// </summary>
        public readonly object ExpectedRemoteServers;
        /// <summary>
        /// Integration Centric Profile ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Profile name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Whether this profile applies to all users in the Workspace by default
        /// </summary>
        public readonly bool UseForAllUsers;
        /// <summary>
        /// Workspace ID
        /// </summary>
        public readonly int WorkspaceId;

        [OutputConstructor]
        private GetIntegrationCentricProfileResult(
            object expectedRemoteServers,

            int id,

            string name,

            bool useForAllUsers,

            int workspaceId)
        {
            ExpectedRemoteServers = expectedRemoteServers;
            Id = id;
            Name = name;
            UseForAllUsers = useForAllUsers;
            WorkspaceId = workspaceId;
        }
    }
}
