// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom
{
    public static class GetMessageReaction
    {
        /// <summary>
        /// A MessageReaction is a reaction emoji made by a user on a message.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const exampleMessageReaction = filescom.getMessageReaction({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_message_reaction = filescom.get_message_reaction(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleMessageReaction = Filescom.GetMessageReaction.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetMessageReaction(ctx, &amp;filescom.LookupMessageReactionArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getmessagereaction" "exampleMessageReaction" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetMessageReactionArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var exampleMessageReaction = FilescomFunctions.getMessageReaction(GetMessageReactionArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   exampleMessageReaction:
        ///     fn::invoke:
        ///       function: filescom:getMessageReaction
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Task<GetMessageReactionResult> InvokeAsync(GetMessageReactionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetMessageReactionResult>("filescom:index/getMessageReaction:getMessageReaction", args ?? new GetMessageReactionArgs(), options.WithDefaults());

        /// <summary>
        /// A MessageReaction is a reaction emoji made by a user on a message.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const exampleMessageReaction = filescom.getMessageReaction({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_message_reaction = filescom.get_message_reaction(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleMessageReaction = Filescom.GetMessageReaction.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetMessageReaction(ctx, &amp;filescom.LookupMessageReactionArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getmessagereaction" "exampleMessageReaction" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetMessageReactionArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var exampleMessageReaction = FilescomFunctions.getMessageReaction(GetMessageReactionArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   exampleMessageReaction:
        ///     fn::invoke:
        ///       function: filescom:getMessageReaction
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetMessageReactionResult> Invoke(GetMessageReactionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetMessageReactionResult>("filescom:index/getMessageReaction:getMessageReaction", args ?? new GetMessageReactionInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// A MessageReaction is a reaction emoji made by a user on a message.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const exampleMessageReaction = filescom.getMessageReaction({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_message_reaction = filescom.get_message_reaction(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleMessageReaction = Filescom.GetMessageReaction.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetMessageReaction(ctx, &amp;filescom.LookupMessageReactionArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getmessagereaction" "exampleMessageReaction" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetMessageReactionArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var exampleMessageReaction = FilescomFunctions.getMessageReaction(GetMessageReactionArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   exampleMessageReaction:
        ///     fn::invoke:
        ///       function: filescom:getMessageReaction
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetMessageReactionResult> Invoke(GetMessageReactionInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetMessageReactionResult>("filescom:index/getMessageReaction:getMessageReaction", args ?? new GetMessageReactionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetMessageReactionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Reaction ID
        /// </summary>
        [Input("id", required: true)]
        public int Id { get; set; }

        public GetMessageReactionArgs()
        {
        }
        public static new GetMessageReactionArgs Empty => new GetMessageReactionArgs();
    }

    public sealed class GetMessageReactionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Reaction ID
        /// </summary>
        [Input("id", required: true)]
        public Input<int> Id { get; set; } = null!;

        public GetMessageReactionInvokeArgs()
        {
        }
        public static new GetMessageReactionInvokeArgs Empty => new GetMessageReactionInvokeArgs();
    }


    [OutputType]
    public sealed class GetMessageReactionResult
    {
        /// <summary>
        /// Emoji used in the reaction.
        /// </summary>
        public readonly string Emoji;
        /// <summary>
        /// Reaction ID
        /// </summary>
        public readonly int Id;

        [OutputConstructor]
        private GetMessageReactionResult(
            string emoji,

            int id)
        {
            Emoji = emoji;
            Id = id;
        }
    }
}
