// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom
{
    public static class GetPermission
    {
        /// <summary>
        /// A Permission object represents a grant of access permission on a specific Path to a User or Group.
        /// 
        /// 
        /// 
        /// They can be optionally recursive or nonrecursive into the subfolders of that path.
        /// 
        /// 
        /// 
        /// A Permission may be applied to a User *or* a Group, but not both at once.
        /// 
        /// 
        /// 
        /// The following table sets forth the available Permission types:
        /// 
        /// 
        /// 
        /// | Permission | Access Level Granted | Automatically Also Includes/Implies Permissions |
        /// 
        /// | --- | ----------- | --------------------- |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`admin`" pulumi-lang-dotnet="`Admin`" pulumi-lang-go="`admin`" pulumi-lang-python="`admin`" pulumi-lang-yaml="`admin`" pulumi-lang-java="`admin`" pulumi-lang-hcl="`admin`"&gt;`admin`&lt;/span&gt; | Able to manage Folder Behaviors, Permissions, and Notifications for the folder. Also grants all other permissions. | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt; | Able to share files and folders via a Bundle (share link). | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt; | Able to read, write, move, delete, and rename files and folders. Also grants the ability to overwrite files upon upload. | &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; | Able to view the history of files and folders and to create email notifications for themselves. | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; | Able to list files and folders, but not download. | none |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt; | Able to list, preview, and download files and folders. | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`readonlySiteAdmin`" pulumi-lang-dotnet="`ReadonlySiteAdmin`" pulumi-lang-go="`readonlySiteAdmin`" pulumi-lang-python="`readonly_site_admin`" pulumi-lang-yaml="`readonlySiteAdmin`" pulumi-lang-java="`readonlySiteAdmin`" pulumi-lang-hcl="`readonly_site_admin`"&gt;`readonlySiteAdmin`&lt;/span&gt; | Able to behave as a read-only Site Admin on a given child site. Only applies to child sites. | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`siteAdmin`" pulumi-lang-dotnet="`SiteAdmin`" pulumi-lang-go="`siteAdmin`" pulumi-lang-python="`site_admin`" pulumi-lang-yaml="`siteAdmin`" pulumi-lang-java="`siteAdmin`" pulumi-lang-hcl="`site_admin`"&gt;`siteAdmin`&lt;/span&gt; | Able to behave as a Site Admin on a given child site. Only applies to child sites. | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt; | Able to upload files, create folders and list subfolders the user has write permission to. | none |
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const examplePermission = filescom.getPermission({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_permission = filescom.get_permission(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var examplePermission = Filescom.GetPermission.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetPermission(ctx, &amp;filescom.LookupPermissionArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getpermission" "examplePermission" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetPermissionArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var examplePermission = FilescomFunctions.getPermission(GetPermissionArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   examplePermission:
        ///     fn::invoke:
        ///       function: filescom:getPermission
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Task<GetPermissionResult> InvokeAsync(GetPermissionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPermissionResult>("filescom:index/getPermission:getPermission", args ?? new GetPermissionArgs(), options.WithDefaults());

        /// <summary>
        /// A Permission object represents a grant of access permission on a specific Path to a User or Group.
        /// 
        /// 
        /// 
        /// They can be optionally recursive or nonrecursive into the subfolders of that path.
        /// 
        /// 
        /// 
        /// A Permission may be applied to a User *or* a Group, but not both at once.
        /// 
        /// 
        /// 
        /// The following table sets forth the available Permission types:
        /// 
        /// 
        /// 
        /// | Permission | Access Level Granted | Automatically Also Includes/Implies Permissions |
        /// 
        /// | --- | ----------- | --------------------- |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`admin`" pulumi-lang-dotnet="`Admin`" pulumi-lang-go="`admin`" pulumi-lang-python="`admin`" pulumi-lang-yaml="`admin`" pulumi-lang-java="`admin`" pulumi-lang-hcl="`admin`"&gt;`admin`&lt;/span&gt; | Able to manage Folder Behaviors, Permissions, and Notifications for the folder. Also grants all other permissions. | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt; | Able to share files and folders via a Bundle (share link). | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt; | Able to read, write, move, delete, and rename files and folders. Also grants the ability to overwrite files upon upload. | &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; | Able to view the history of files and folders and to create email notifications for themselves. | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; | Able to list files and folders, but not download. | none |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt; | Able to list, preview, and download files and folders. | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`readonlySiteAdmin`" pulumi-lang-dotnet="`ReadonlySiteAdmin`" pulumi-lang-go="`readonlySiteAdmin`" pulumi-lang-python="`readonly_site_admin`" pulumi-lang-yaml="`readonlySiteAdmin`" pulumi-lang-java="`readonlySiteAdmin`" pulumi-lang-hcl="`readonly_site_admin`"&gt;`readonlySiteAdmin`&lt;/span&gt; | Able to behave as a read-only Site Admin on a given child site. Only applies to child sites. | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`siteAdmin`" pulumi-lang-dotnet="`SiteAdmin`" pulumi-lang-go="`siteAdmin`" pulumi-lang-python="`site_admin`" pulumi-lang-yaml="`siteAdmin`" pulumi-lang-java="`siteAdmin`" pulumi-lang-hcl="`site_admin`"&gt;`siteAdmin`&lt;/span&gt; | Able to behave as a Site Admin on a given child site. Only applies to child sites. | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt; | Able to upload files, create folders and list subfolders the user has write permission to. | none |
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const examplePermission = filescom.getPermission({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_permission = filescom.get_permission(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var examplePermission = Filescom.GetPermission.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetPermission(ctx, &amp;filescom.LookupPermissionArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getpermission" "examplePermission" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetPermissionArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var examplePermission = FilescomFunctions.getPermission(GetPermissionArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   examplePermission:
        ///     fn::invoke:
        ///       function: filescom:getPermission
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetPermissionResult> Invoke(GetPermissionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPermissionResult>("filescom:index/getPermission:getPermission", args ?? new GetPermissionInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// A Permission object represents a grant of access permission on a specific Path to a User or Group.
        /// 
        /// 
        /// 
        /// They can be optionally recursive or nonrecursive into the subfolders of that path.
        /// 
        /// 
        /// 
        /// A Permission may be applied to a User *or* a Group, but not both at once.
        /// 
        /// 
        /// 
        /// The following table sets forth the available Permission types:
        /// 
        /// 
        /// 
        /// | Permission | Access Level Granted | Automatically Also Includes/Implies Permissions |
        /// 
        /// | --- | ----------- | --------------------- |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`admin`" pulumi-lang-dotnet="`Admin`" pulumi-lang-go="`admin`" pulumi-lang-python="`admin`" pulumi-lang-yaml="`admin`" pulumi-lang-java="`admin`" pulumi-lang-hcl="`admin`"&gt;`admin`&lt;/span&gt; | Able to manage Folder Behaviors, Permissions, and Notifications for the folder. Also grants all other permissions. | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt; | Able to share files and folders via a Bundle (share link). | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt; | Able to read, write, move, delete, and rename files and folders. Also grants the ability to overwrite files upon upload. | &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; | Able to view the history of files and folders and to create email notifications for themselves. | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; | Able to list files and folders, but not download. | none |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt; | Able to list, preview, and download files and folders. | &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`readonlySiteAdmin`" pulumi-lang-dotnet="`ReadonlySiteAdmin`" pulumi-lang-go="`readonlySiteAdmin`" pulumi-lang-python="`readonly_site_admin`" pulumi-lang-yaml="`readonlySiteAdmin`" pulumi-lang-java="`readonlySiteAdmin`" pulumi-lang-hcl="`readonly_site_admin`"&gt;`readonlySiteAdmin`&lt;/span&gt; | Able to behave as a read-only Site Admin on a given child site. Only applies to child sites. | &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`siteAdmin`" pulumi-lang-dotnet="`SiteAdmin`" pulumi-lang-go="`siteAdmin`" pulumi-lang-python="`site_admin`" pulumi-lang-yaml="`siteAdmin`" pulumi-lang-java="`siteAdmin`" pulumi-lang-hcl="`site_admin`"&gt;`siteAdmin`&lt;/span&gt; | Able to behave as a Site Admin on a given child site. Only applies to child sites. | &lt;span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`"&gt;`bundle`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`"&gt;`full`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`"&gt;`readonly`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`"&gt;`list`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`"&gt;`history`&lt;/span&gt; |
        /// 
        /// | &lt;span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`"&gt;`writeonly`&lt;/span&gt; | Able to upload files, create folders and list subfolders the user has write permission to. | none |
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```typescript
        /// import * as pulumi from "@pulumi/pulumi";
        /// import * as filescom from "pulumi-filescom";
        /// 
        /// const examplePermission = filescom.getPermission({
        ///     id: 1,
        /// });
        /// ```
        /// ```python
        /// import pulumi
        /// import pulumi_filescom as filescom
        /// 
        /// example_permission = filescom.get_permission(id=1)
        /// ```
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Filescom = Jschady.Filescom;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var examplePermission = Filescom.GetPermission.Invoke(new()
        ///     {
        ///         Id = 1,
        ///     });
        /// 
        /// });
        /// ```
        /// ```go
        /// package main
        /// 
        /// import (
        /// 	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
        /// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
        /// )
        /// 
        /// func main() {
        /// 	pulumi.Run(func(ctx *pulumi.Context) error {
        /// 		_, err := filescom.GetPermission(ctx, &amp;filescom.LookupPermissionArgs{
        /// 			Id: 1,
        /// 		}, nil)
        /// 		if err != nil {
        /// 			return err
        /// 		}
        /// 		return nil
        /// 	})
        /// }
        /// ```
        /// ```hcl
        /// pulumi {
        ///   required_providers {
        ///     filescom = {
        ///       source = "pulumi/filescom"
        ///     }
        ///   }
        /// }
        /// 
        /// data "filescom_getpermission" "examplePermission" {
        ///   id = 1
        /// }
        /// ```
        /// ```java
        /// package generated_program;
        /// 
        /// import com.pulumi.Context;
        /// import com.pulumi.Pulumi;
        /// import com.pulumi.core.Output;
        /// import com.pulumi.filescom.FilescomFunctions;
        /// import com.pulumi.filescom.inputs.GetPermissionArgs;
        /// import java.util.ArrayList;
        /// import java.util.Arrays;
        /// import java.util.Map;
        /// import java.io.File;
        /// import java.nio.file.Files;
        /// import java.nio.file.Paths;
        /// 
        /// public class App {
        ///     public static void main(String[] args) {
        ///         Pulumi.run(App::stack);
        ///     }
        /// 
        ///     public static void stack(Context ctx) {
        ///         final var examplePermission = FilescomFunctions.getPermission(GetPermissionArgs.builder()
        ///             .id(1)
        ///             .build());
        /// 
        ///     }
        /// }
        /// ```
        /// ```yaml
        /// variables:
        ///   examplePermission:
        ///     fn::invoke:
        ///       function: filescom:getPermission
        ///       arguments:
        ///         id: 1
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetPermissionResult> Invoke(GetPermissionInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPermissionResult>("filescom:index/getPermission:getPermission", args ?? new GetPermissionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPermissionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Permission ID
        /// </summary>
        [Input("id", required: true)]
        public int Id { get; set; }

        public GetPermissionArgs()
        {
        }
        public static new GetPermissionArgs Empty => new GetPermissionArgs();
    }

    public sealed class GetPermissionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Permission ID
        /// </summary>
        [Input("id", required: true)]
        public Input<int> Id { get; set; } = null!;

        public GetPermissionInvokeArgs()
        {
        }
        public static new GetPermissionInvokeArgs Empty => new GetPermissionInvokeArgs();
    }


    [OutputType]
    public sealed class GetPermissionResult
    {
        /// <summary>
        /// Group ID
        /// </summary>
        public readonly int GroupId;
        /// <summary>
        /// Group IDs when this permission requires multiple groups
        /// </summary>
        public readonly ImmutableArray<int> GroupIds;
        /// <summary>
        /// Group name (if applicable)
        /// </summary>
        public readonly string GroupName;
        /// <summary>
        /// Group names when this permission requires multiple groups
        /// </summary>
        public readonly ImmutableArray<string> GroupNames;
        /// <summary>
        /// Permission ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Partner ID (if applicable)
        /// </summary>
        public readonly int PartnerId;
        /// <summary>
        /// Partner name (if applicable)
        /// </summary>
        public readonly string PartnerName;
        /// <summary>
        /// Path. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// Permission type.  See the table referenced in the documentation for an explanation of each permission.
        /// </summary>
        public readonly string Permission;
        /// <summary>
        /// Recursive: does this permission apply to subfolders?
        /// </summary>
        public readonly bool Recursive;
        /// <summary>
        /// Site ID
        /// </summary>
        public readonly int SiteId;
        /// <summary>
        /// User ID
        /// </summary>
        public readonly int UserId;
        /// <summary>
        /// Username (if applicable)
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private GetPermissionResult(
            int groupId,

            ImmutableArray<int> groupIds,

            string groupName,

            ImmutableArray<string> groupNames,

            int id,

            int partnerId,

            string partnerName,

            string path,

            string permission,

            bool recursive,

            int siteId,

            int userId,

            string username)
        {
            GroupId = groupId;
            GroupIds = groupIds;
            GroupName = groupName;
            GroupNames = groupNames;
            Id = id;
            PartnerId = partnerId;
            PartnerName = partnerName;
            Path = path;
            Permission = permission;
            Recursive = recursive;
            SiteId = siteId;
            UserId = userId;
            Username = username;
        }
    }
}
