// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// &lt;!--Start PulumiCodeChooser --&gt;
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Filescom = Jschady.Filescom;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleSiemHttpDestination = new Filescom.SiemHttpDestination("example_siem_http_destination", new()
    ///     {
    ///         Name = "example",
    ///         AdditionalHeaders = new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["key"] = "example value",
    ///         },
    ///         SendingActive = true,
    ///         GenericPayloadType = "example",
    ///         FileDestinationPath = "example",
    ///         FileFormat = "example",
    ///         FileIntervalMinutes = 1,
    ///         AzureDcrImmutableId = "example",
    ///         AzureStreamName = "example",
    ///         AzureOauthClientCredentialsTenantId = "example",
    ///         AzureOauthClientCredentialsClientId = "example",
    ///         QradarUsername = "example",
    ///         ActionSendEnabled = true,
    ///         SftpActionSendEnabled = true,
    ///         FtpActionSendEnabled = true,
    ///         WebDavActionSendEnabled = true,
    ///         SyncSendEnabled = true,
    ///         OutboundConnectionSendEnabled = true,
    ///         AutomationSendEnabled = true,
    ///         ApiRequestSendEnabled = true,
    ///         PublicHostingRequestSendEnabled = true,
    ///         EmailSendEnabled = true,
    ///         ExavaultApiRequestSendEnabled = true,
    ///         SettingsChangeSendEnabled = true,
    ///         DestinationType = "example",
    ///         DestinationUrl = "example",
    ///     });
    /// 
    /// });
    /// ```
    /// &lt;!--End PulumiCodeChooser --&gt;
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// Siem Http Destinations can be imported by specifying the id.
    /// 
    /// ```sh
    /// $ pulumi import filescom:index/siemHttpDestination:SiemHttpDestination example_siem_http_destination 1
    /// ```
    /// </summary>
    [FilescomResourceType("filescom:index/siemHttpDestination:SiemHttpDestination")]
    public partial class SiemHttpDestination : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("actionEntriesSent")]
        public Output<int> ActionEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for action logs.
        /// </summary>
        [Output("actionSendEnabled")]
        public Output<bool> ActionSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Additional HTTP Headers included in calls to the destination URL
        /// </summary>
        [Output("additionalHeaders")]
        public Output<object> AdditionalHeaders { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("apiRequestEntriesSent")]
        public Output<int> ApiRequestEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" apiRequest " pulumi-lang-dotnet=" ApiRequest " pulumi-lang-go=" apiRequest " pulumi-lang-python=" api_request " pulumi-lang-yaml=" apiRequest " pulumi-lang-java=" apiRequest " pulumi-lang-hcl=" api_request "&gt; apiRequest &lt;/span&gt;logs.
        /// </summary>
        [Output("apiRequestSendEnabled")]
        public Output<bool> ApiRequestSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("automationEntriesSent")]
        public Output<int> AutomationEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for automation logs.
        /// </summary>
        [Output("automationSendEnabled")]
        public Output<bool> AutomationSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Immutable ID of the Data Collection Rule.
        /// </summary>
        [Output("azureDcrImmutableId")]
        public Output<string> AzureDcrImmutableId { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Client ID.
        /// </summary>
        [Output("azureOauthClientCredentialsClientId")]
        public Output<string> AzureOauthClientCredentialsClientId { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: azure. Client Credentials OAuth Client Secret.
        /// </summary>
        [Output("azureOauthClientCredentialsClientSecret")]
        public Output<string?> AzureOauthClientCredentialsClientSecret { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Client Secret.
        /// </summary>
        [Output("azureOauthClientCredentialsClientSecretMasked")]
        public Output<string> AzureOauthClientCredentialsClientSecretMasked { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Tenant ID.
        /// </summary>
        [Output("azureOauthClientCredentialsTenantId")]
        public Output<string> AzureOauthClientCredentialsTenantId { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: azure. Name of the stream in the DCR that represents the destination table.
        /// </summary>
        [Output("azureStreamName")]
        public Output<string> AzureStreamName { get; private set; } = null!;

        /// <summary>
        /// Connection Test Entry
        /// </summary>
        [Output("connectionTestEntry")]
        public Output<string> ConnectionTestEntry { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: crowdstrike. Authentication token provided by Crowdstrike.
        /// </summary>
        [Output("crowdstrikeToken")]
        public Output<string?> CrowdstrikeToken { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: crowdstrike. Authentication token provided by Crowdstrike.
        /// </summary>
        [Output("crowdstrikeTokenMasked")]
        public Output<string> CrowdstrikeTokenMasked { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: datadog. API key provided by Datadog.
        /// </summary>
        [Output("datadogApiKey")]
        public Output<string?> DatadogApiKey { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: datadog. API key provided by Datadog.
        /// </summary>
        [Output("datadogApiKeyMasked")]
        public Output<string> DatadogApiKeyMasked { get; private set; } = null!;

        /// <summary>
        /// Destination Type
        /// </summary>
        [Output("destinationType")]
        public Output<string> DestinationType { get; private set; } = null!;

        /// <summary>
        /// Destination Url
        /// </summary>
        [Output("destinationUrl")]
        public Output<string> DestinationUrl { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("emailEntriesSent")]
        public Output<int> EmailEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for email logs.
        /// </summary>
        [Output("emailSendEnabled")]
        public Output<bool> EmailSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("exavaultApiRequestEntriesSent")]
        public Output<int> ExavaultApiRequestEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" exavaultApiRequest " pulumi-lang-dotnet=" ExavaultApiRequest " pulumi-lang-go=" exavaultApiRequest " pulumi-lang-python=" exavault_api_request " pulumi-lang-yaml=" exavaultApiRequest " pulumi-lang-java=" exavaultApiRequest " pulumi-lang-hcl=" exavault_api_request "&gt; exavaultApiRequest &lt;/span&gt;logs.
        /// </summary>
        [Output("exavaultApiRequestSendEnabled")]
        public Output<bool> ExavaultApiRequestSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: file. Destination folder path on Files.com.
        /// </summary>
        [Output("fileDestinationPath")]
        public Output<string> FileDestinationPath { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: file. Generated file format.
        /// </summary>
        [Output("fileFormat")]
        public Output<string> FileFormat { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: file. Interval, in minutes, between file deliveries.
        /// </summary>
        [Output("fileIntervalMinutes")]
        public Output<int> FileIntervalMinutes { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("ftpActionEntriesSent")]
        public Output<int> FtpActionEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" ftpAction " pulumi-lang-dotnet=" FtpAction " pulumi-lang-go=" ftpAction " pulumi-lang-python=" ftp_action " pulumi-lang-yaml=" ftpAction " pulumi-lang-java=" ftpAction " pulumi-lang-hcl=" ftp_action "&gt; ftpAction &lt;/span&gt;logs.
        /// </summary>
        [Output("ftpActionSendEnabled")]
        public Output<bool> FtpActionSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: generic. Indicates the type of HTTP body. Can be&lt;span pulumi-lang-nodejs=" jsonNewline " pulumi-lang-dotnet=" JsonNewline " pulumi-lang-go=" jsonNewline " pulumi-lang-python=" json_newline " pulumi-lang-yaml=" jsonNewline " pulumi-lang-java=" jsonNewline " pulumi-lang-hcl=" json_newline "&gt; jsonNewline &lt;/span&gt;or json_array.&lt;span pulumi-lang-nodejs=" jsonNewline " pulumi-lang-dotnet=" JsonNewline " pulumi-lang-go=" jsonNewline " pulumi-lang-python=" json_newline " pulumi-lang-yaml=" jsonNewline " pulumi-lang-java=" jsonNewline " pulumi-lang-hcl=" json_newline "&gt; jsonNewline &lt;/span&gt;is multiple log entries as JSON separated by newlines.&lt;span pulumi-lang-nodejs=" jsonArray " pulumi-lang-dotnet=" JsonArray " pulumi-lang-go=" jsonArray " pulumi-lang-python=" json_array " pulumi-lang-yaml=" jsonArray " pulumi-lang-java=" jsonArray " pulumi-lang-hcl=" json_array "&gt; jsonArray &lt;/span&gt;is a single JSON array containing multiple log entries as JSON.
        /// </summary>
        [Output("genericPayloadType")]
        public Output<string> GenericPayloadType { get; private set; } = null!;

        /// <summary>
        /// Duration of the last HTTP Call in milliseconds
        /// </summary>
        [Output("lastHttpCallDurationMs")]
        public Output<int> LastHttpCallDurationMs { get; private set; } = null!;

        /// <summary>
        /// Last HTTP Call Error Message if applicable
        /// </summary>
        [Output("lastHttpCallErrorMessage")]
        public Output<string> LastHttpCallErrorMessage { get; private set; } = null!;

        /// <summary>
        /// Last HTTP Call Response Body. Large responses are truncated.
        /// </summary>
        [Output("lastHttpCallResponseBody")]
        public Output<string> LastHttpCallResponseBody { get; private set; } = null!;

        /// <summary>
        /// Last HTTP Call Response Code
        /// </summary>
        [Output("lastHttpCallResponseCode")]
        public Output<int> LastHttpCallResponseCode { get; private set; } = null!;

        /// <summary>
        /// Was the last HTTP call made successful?
        /// </summary>
        [Output("lastHttpCallSuccess")]
        public Output<bool> LastHttpCallSuccess { get; private set; } = null!;

        /// <summary>
        /// Type of URL that was last called. Can be &lt;span pulumi-lang-nodejs="`destinationUrl`" pulumi-lang-dotnet="`DestinationUrl`" pulumi-lang-go="`destinationUrl`" pulumi-lang-python="`destination_url`" pulumi-lang-yaml="`destinationUrl`" pulumi-lang-java="`destinationUrl`" pulumi-lang-hcl="`destination_url`"&gt;`destinationUrl`&lt;/span&gt; or &lt;span pulumi-lang-nodejs="`azureOauthClientCredentialsUrl`" pulumi-lang-dotnet="`AzureOauthClientCredentialsUrl`" pulumi-lang-go="`azureOauthClientCredentialsUrl`" pulumi-lang-python="`azure_oauth_client_credentials_url`" pulumi-lang-yaml="`azureOauthClientCredentialsUrl`" pulumi-lang-java="`azureOauthClientCredentialsUrl`" pulumi-lang-hcl="`azure_oauth_client_credentials_url`"&gt;`azureOauthClientCredentialsUrl`&lt;/span&gt;
        /// </summary>
        [Output("lastHttpCallTargetType")]
        public Output<string> LastHttpCallTargetType { get; private set; } = null!;

        /// <summary>
        /// Time of Last HTTP Call
        /// </summary>
        [Output("lastHttpCallTime")]
        public Output<string> LastHttpCallTime { get; private set; } = null!;

        /// <summary>
        /// Time of Most Recent Successful HTTP Call
        /// </summary>
        [Output("mostRecentHttpCallSuccessTime")]
        public Output<string> MostRecentHttpCallSuccessTime { get; private set; } = null!;

        /// <summary>
        /// Name for this Destination
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: new_relic. API key provided by New Relic.
        /// </summary>
        [Output("newRelicApiKey")]
        public Output<string?> NewRelicApiKey { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: new_relic. API key provided by New Relic.
        /// </summary>
        [Output("newRelicApiKeyMasked")]
        public Output<string> NewRelicApiKeyMasked { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("outboundConnectionEntriesSent")]
        public Output<int> OutboundConnectionEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" outboundConnection " pulumi-lang-dotnet=" OutboundConnection " pulumi-lang-go=" outboundConnection " pulumi-lang-python=" outbound_connection " pulumi-lang-yaml=" outboundConnection " pulumi-lang-java=" outboundConnection " pulumi-lang-hcl=" outbound_connection "&gt; outboundConnection &lt;/span&gt;logs.
        /// </summary>
        [Output("outboundConnectionSendEnabled")]
        public Output<bool> OutboundConnectionSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("publicHostingRequestEntriesSent")]
        public Output<int> PublicHostingRequestEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" publicHostingRequest " pulumi-lang-dotnet=" PublicHostingRequest " pulumi-lang-go=" publicHostingRequest " pulumi-lang-python=" public_hosting_request " pulumi-lang-yaml=" publicHostingRequest " pulumi-lang-java=" publicHostingRequest " pulumi-lang-hcl=" public_hosting_request "&gt; publicHostingRequest &lt;/span&gt;logs.
        /// </summary>
        [Output("publicHostingRequestSendEnabled")]
        public Output<bool> PublicHostingRequestSendEnabled { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: qradar. Basic auth password provided by QRadar.
        /// </summary>
        [Output("qradarPassword")]
        public Output<string?> QradarPassword { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: qradar. Basic auth password provided by QRadar.
        /// </summary>
        [Output("qradarPasswordMasked")]
        public Output<string> QradarPasswordMasked { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: qradar. Basic auth username provided by QRadar.
        /// </summary>
        [Output("qradarUsername")]
        public Output<string> QradarUsername { get; private set; } = null!;

        /// <summary>
        /// Whether this SIEM HTTP Destination is currently being sent to or not
        /// </summary>
        [Output("sendingActive")]
        public Output<bool> SendingActive { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("settingsChangeEntriesSent")]
        public Output<int> SettingsChangeEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" settingsChange " pulumi-lang-dotnet=" SettingsChange " pulumi-lang-go=" settingsChange " pulumi-lang-python=" settings_change " pulumi-lang-yaml=" settingsChange " pulumi-lang-java=" settingsChange " pulumi-lang-hcl=" settings_change "&gt; settingsChange &lt;/span&gt;logs.
        /// </summary>
        [Output("settingsChangeSendEnabled")]
        public Output<bool> SettingsChangeSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("sftpActionEntriesSent")]
        public Output<int> SftpActionEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" sftpAction " pulumi-lang-dotnet=" SftpAction " pulumi-lang-go=" sftpAction " pulumi-lang-python=" sftp_action " pulumi-lang-yaml=" sftpAction " pulumi-lang-java=" sftpAction " pulumi-lang-hcl=" sftp_action "&gt; sftpAction &lt;/span&gt;logs.
        /// </summary>
        [Output("sftpActionSendEnabled")]
        public Output<bool> SftpActionSendEnabled { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: solar_winds. Authentication token provided by Solar Winds.
        /// </summary>
        [Output("solarWindsToken")]
        public Output<string?> SolarWindsToken { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination type: solar_winds. Authentication token provided by Solar Winds.
        /// </summary>
        [Output("solarWindsTokenMasked")]
        public Output<string> SolarWindsTokenMasked { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination types: splunk, splunk_compatible. Authentication token for the destination.
        /// </summary>
        [Output("splunkToken")]
        public Output<string?> SplunkToken { get; private set; } = null!;

        /// <summary>
        /// Applicable only for destination types: splunk, splunk_compatible. Authentication token for the destination.
        /// </summary>
        [Output("splunkTokenMasked")]
        public Output<string> SplunkTokenMasked { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("syncEntriesSent")]
        public Output<int> SyncEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for sync logs.
        /// </summary>
        [Output("syncSendEnabled")]
        public Output<bool> SyncSendEnabled { get; private set; } = null!;

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Output("webDavActionEntriesSent")]
        public Output<int> WebDavActionEntriesSent { get; private set; } = null!;

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" webDavAction " pulumi-lang-dotnet=" WebDavAction " pulumi-lang-go=" webDavAction " pulumi-lang-python=" web_dav_action " pulumi-lang-yaml=" webDavAction " pulumi-lang-java=" webDavAction " pulumi-lang-hcl=" web_dav_action "&gt; webDavAction &lt;/span&gt;logs.
        /// </summary>
        [Output("webDavActionSendEnabled")]
        public Output<bool> WebDavActionSendEnabled { get; private set; } = null!;


        /// <summary>
        /// Create a SiemHttpDestination resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SiemHttpDestination(string name, SiemHttpDestinationArgs args, CustomResourceOptions? options = null)
            : base("filescom:index/siemHttpDestination:SiemHttpDestination", name, args ?? new SiemHttpDestinationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SiemHttpDestination(string name, Input<string> id, SiemHttpDestinationState? state = null, CustomResourceOptions? options = null)
            : base("filescom:index/siemHttpDestination:SiemHttpDestination", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jschady/pulumi-filescom",
                AdditionalSecretOutputs =
                {
                    "azureOauthClientCredentialsClientSecret",
                    "crowdstrikeToken",
                    "datadogApiKey",
                    "newRelicApiKey",
                    "qradarPassword",
                    "solarWindsToken",
                    "splunkToken",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SiemHttpDestination resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SiemHttpDestination Get(string name, Input<string> id, SiemHttpDestinationState? state = null, CustomResourceOptions? options = null)
        {
            return new SiemHttpDestination(name, id, state, options);
        }
    }

    public sealed class SiemHttpDestinationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether or not sending is enabled for action logs.
        /// </summary>
        [Input("actionSendEnabled")]
        public Input<bool>? ActionSendEnabled { get; set; }

        /// <summary>
        /// Additional HTTP Headers included in calls to the destination URL
        /// </summary>
        [Input("additionalHeaders")]
        public Input<object>? AdditionalHeaders { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" apiRequest " pulumi-lang-dotnet=" ApiRequest " pulumi-lang-go=" apiRequest " pulumi-lang-python=" api_request " pulumi-lang-yaml=" apiRequest " pulumi-lang-java=" apiRequest " pulumi-lang-hcl=" api_request "&gt; apiRequest &lt;/span&gt;logs.
        /// </summary>
        [Input("apiRequestSendEnabled")]
        public Input<bool>? ApiRequestSendEnabled { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for automation logs.
        /// </summary>
        [Input("automationSendEnabled")]
        public Input<bool>? AutomationSendEnabled { get; set; }

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Immutable ID of the Data Collection Rule.
        /// </summary>
        [Input("azureDcrImmutableId")]
        public Input<string>? AzureDcrImmutableId { get; set; }

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Client ID.
        /// </summary>
        [Input("azureOauthClientCredentialsClientId")]
        public Input<string>? AzureOauthClientCredentialsClientId { get; set; }

        [Input("azureOauthClientCredentialsClientSecret")]
        private Input<string>? _azureOauthClientCredentialsClientSecret;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: azure. Client Credentials OAuth Client Secret.
        /// </summary>
        public Input<string>? AzureOauthClientCredentialsClientSecret
        {
            get => _azureOauthClientCredentialsClientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _azureOauthClientCredentialsClientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Tenant ID.
        /// </summary>
        [Input("azureOauthClientCredentialsTenantId")]
        public Input<string>? AzureOauthClientCredentialsTenantId { get; set; }

        /// <summary>
        /// Applicable only for destination type: azure. Name of the stream in the DCR that represents the destination table.
        /// </summary>
        [Input("azureStreamName")]
        public Input<string>? AzureStreamName { get; set; }

        [Input("crowdstrikeToken")]
        private Input<string>? _crowdstrikeToken;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: crowdstrike. Authentication token provided by Crowdstrike.
        /// </summary>
        public Input<string>? CrowdstrikeToken
        {
            get => _crowdstrikeToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _crowdstrikeToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("datadogApiKey")]
        private Input<string>? _datadogApiKey;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: datadog. API key provided by Datadog.
        /// </summary>
        public Input<string>? DatadogApiKey
        {
            get => _datadogApiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _datadogApiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Destination Type
        /// </summary>
        [Input("destinationType", required: true)]
        public Input<string> DestinationType { get; set; } = null!;

        /// <summary>
        /// Destination Url
        /// </summary>
        [Input("destinationUrl")]
        public Input<string>? DestinationUrl { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for email logs.
        /// </summary>
        [Input("emailSendEnabled")]
        public Input<bool>? EmailSendEnabled { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" exavaultApiRequest " pulumi-lang-dotnet=" ExavaultApiRequest " pulumi-lang-go=" exavaultApiRequest " pulumi-lang-python=" exavault_api_request " pulumi-lang-yaml=" exavaultApiRequest " pulumi-lang-java=" exavaultApiRequest " pulumi-lang-hcl=" exavault_api_request "&gt; exavaultApiRequest &lt;/span&gt;logs.
        /// </summary>
        [Input("exavaultApiRequestSendEnabled")]
        public Input<bool>? ExavaultApiRequestSendEnabled { get; set; }

        /// <summary>
        /// Applicable only for destination type: file. Destination folder path on Files.com.
        /// </summary>
        [Input("fileDestinationPath")]
        public Input<string>? FileDestinationPath { get; set; }

        /// <summary>
        /// Applicable only for destination type: file. Generated file format.
        /// </summary>
        [Input("fileFormat")]
        public Input<string>? FileFormat { get; set; }

        /// <summary>
        /// Applicable only for destination type: file. Interval, in minutes, between file deliveries.
        /// </summary>
        [Input("fileIntervalMinutes")]
        public Input<int>? FileIntervalMinutes { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" ftpAction " pulumi-lang-dotnet=" FtpAction " pulumi-lang-go=" ftpAction " pulumi-lang-python=" ftp_action " pulumi-lang-yaml=" ftpAction " pulumi-lang-java=" ftpAction " pulumi-lang-hcl=" ftp_action "&gt; ftpAction &lt;/span&gt;logs.
        /// </summary>
        [Input("ftpActionSendEnabled")]
        public Input<bool>? FtpActionSendEnabled { get; set; }

        /// <summary>
        /// Applicable only for destination type: generic. Indicates the type of HTTP body. Can be&lt;span pulumi-lang-nodejs=" jsonNewline " pulumi-lang-dotnet=" JsonNewline " pulumi-lang-go=" jsonNewline " pulumi-lang-python=" json_newline " pulumi-lang-yaml=" jsonNewline " pulumi-lang-java=" jsonNewline " pulumi-lang-hcl=" json_newline "&gt; jsonNewline &lt;/span&gt;or json_array.&lt;span pulumi-lang-nodejs=" jsonNewline " pulumi-lang-dotnet=" JsonNewline " pulumi-lang-go=" jsonNewline " pulumi-lang-python=" json_newline " pulumi-lang-yaml=" jsonNewline " pulumi-lang-java=" jsonNewline " pulumi-lang-hcl=" json_newline "&gt; jsonNewline &lt;/span&gt;is multiple log entries as JSON separated by newlines.&lt;span pulumi-lang-nodejs=" jsonArray " pulumi-lang-dotnet=" JsonArray " pulumi-lang-go=" jsonArray " pulumi-lang-python=" json_array " pulumi-lang-yaml=" jsonArray " pulumi-lang-java=" jsonArray " pulumi-lang-hcl=" json_array "&gt; jsonArray &lt;/span&gt;is a single JSON array containing multiple log entries as JSON.
        /// </summary>
        [Input("genericPayloadType")]
        public Input<string>? GenericPayloadType { get; set; }

        /// <summary>
        /// Name for this Destination
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("newRelicApiKey")]
        private Input<string>? _newRelicApiKey;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: new_relic. API key provided by New Relic.
        /// </summary>
        public Input<string>? NewRelicApiKey
        {
            get => _newRelicApiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _newRelicApiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" outboundConnection " pulumi-lang-dotnet=" OutboundConnection " pulumi-lang-go=" outboundConnection " pulumi-lang-python=" outbound_connection " pulumi-lang-yaml=" outboundConnection " pulumi-lang-java=" outboundConnection " pulumi-lang-hcl=" outbound_connection "&gt; outboundConnection &lt;/span&gt;logs.
        /// </summary>
        [Input("outboundConnectionSendEnabled")]
        public Input<bool>? OutboundConnectionSendEnabled { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" publicHostingRequest " pulumi-lang-dotnet=" PublicHostingRequest " pulumi-lang-go=" publicHostingRequest " pulumi-lang-python=" public_hosting_request " pulumi-lang-yaml=" publicHostingRequest " pulumi-lang-java=" publicHostingRequest " pulumi-lang-hcl=" public_hosting_request "&gt; publicHostingRequest &lt;/span&gt;logs.
        /// </summary>
        [Input("publicHostingRequestSendEnabled")]
        public Input<bool>? PublicHostingRequestSendEnabled { get; set; }

        [Input("qradarPassword")]
        private Input<string>? _qradarPassword;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: qradar. Basic auth password provided by QRadar.
        /// </summary>
        public Input<string>? QradarPassword
        {
            get => _qradarPassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _qradarPassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination type: qradar. Basic auth username provided by QRadar.
        /// </summary>
        [Input("qradarUsername")]
        public Input<string>? QradarUsername { get; set; }

        /// <summary>
        /// Whether this SIEM HTTP Destination is currently being sent to or not
        /// </summary>
        [Input("sendingActive")]
        public Input<bool>? SendingActive { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" settingsChange " pulumi-lang-dotnet=" SettingsChange " pulumi-lang-go=" settingsChange " pulumi-lang-python=" settings_change " pulumi-lang-yaml=" settingsChange " pulumi-lang-java=" settingsChange " pulumi-lang-hcl=" settings_change "&gt; settingsChange &lt;/span&gt;logs.
        /// </summary>
        [Input("settingsChangeSendEnabled")]
        public Input<bool>? SettingsChangeSendEnabled { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" sftpAction " pulumi-lang-dotnet=" SftpAction " pulumi-lang-go=" sftpAction " pulumi-lang-python=" sftp_action " pulumi-lang-yaml=" sftpAction " pulumi-lang-java=" sftpAction " pulumi-lang-hcl=" sftp_action "&gt; sftpAction &lt;/span&gt;logs.
        /// </summary>
        [Input("sftpActionSendEnabled")]
        public Input<bool>? SftpActionSendEnabled { get; set; }

        [Input("solarWindsToken")]
        private Input<string>? _solarWindsToken;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: solar_winds. Authentication token provided by Solar Winds.
        /// </summary>
        public Input<string>? SolarWindsToken
        {
            get => _solarWindsToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _solarWindsToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("splunkToken")]
        private Input<string>? _splunkToken;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination types: splunk, splunk_compatible. Authentication token for the destination.
        /// </summary>
        public Input<string>? SplunkToken
        {
            get => _splunkToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _splunkToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether or not sending is enabled for sync logs.
        /// </summary>
        [Input("syncSendEnabled")]
        public Input<bool>? SyncSendEnabled { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" webDavAction " pulumi-lang-dotnet=" WebDavAction " pulumi-lang-go=" webDavAction " pulumi-lang-python=" web_dav_action " pulumi-lang-yaml=" webDavAction " pulumi-lang-java=" webDavAction " pulumi-lang-hcl=" web_dav_action "&gt; webDavAction &lt;/span&gt;logs.
        /// </summary>
        [Input("webDavActionSendEnabled")]
        public Input<bool>? WebDavActionSendEnabled { get; set; }

        public SiemHttpDestinationArgs()
        {
        }
        public static new SiemHttpDestinationArgs Empty => new SiemHttpDestinationArgs();
    }

    public sealed class SiemHttpDestinationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("actionEntriesSent")]
        public Input<int>? ActionEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for action logs.
        /// </summary>
        [Input("actionSendEnabled")]
        public Input<bool>? ActionSendEnabled { get; set; }

        /// <summary>
        /// Additional HTTP Headers included in calls to the destination URL
        /// </summary>
        [Input("additionalHeaders")]
        public Input<object>? AdditionalHeaders { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("apiRequestEntriesSent")]
        public Input<int>? ApiRequestEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" apiRequest " pulumi-lang-dotnet=" ApiRequest " pulumi-lang-go=" apiRequest " pulumi-lang-python=" api_request " pulumi-lang-yaml=" apiRequest " pulumi-lang-java=" apiRequest " pulumi-lang-hcl=" api_request "&gt; apiRequest &lt;/span&gt;logs.
        /// </summary>
        [Input("apiRequestSendEnabled")]
        public Input<bool>? ApiRequestSendEnabled { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("automationEntriesSent")]
        public Input<int>? AutomationEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for automation logs.
        /// </summary>
        [Input("automationSendEnabled")]
        public Input<bool>? AutomationSendEnabled { get; set; }

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Immutable ID of the Data Collection Rule.
        /// </summary>
        [Input("azureDcrImmutableId")]
        public Input<string>? AzureDcrImmutableId { get; set; }

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Client ID.
        /// </summary>
        [Input("azureOauthClientCredentialsClientId")]
        public Input<string>? AzureOauthClientCredentialsClientId { get; set; }

        [Input("azureOauthClientCredentialsClientSecret")]
        private Input<string>? _azureOauthClientCredentialsClientSecret;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: azure. Client Credentials OAuth Client Secret.
        /// </summary>
        public Input<string>? AzureOauthClientCredentialsClientSecret
        {
            get => _azureOauthClientCredentialsClientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _azureOauthClientCredentialsClientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Client Secret.
        /// </summary>
        [Input("azureOauthClientCredentialsClientSecretMasked")]
        public Input<string>? AzureOauthClientCredentialsClientSecretMasked { get; set; }

        /// <summary>
        /// Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Tenant ID.
        /// </summary>
        [Input("azureOauthClientCredentialsTenantId")]
        public Input<string>? AzureOauthClientCredentialsTenantId { get; set; }

        /// <summary>
        /// Applicable only for destination type: azure. Name of the stream in the DCR that represents the destination table.
        /// </summary>
        [Input("azureStreamName")]
        public Input<string>? AzureStreamName { get; set; }

        /// <summary>
        /// Connection Test Entry
        /// </summary>
        [Input("connectionTestEntry")]
        public Input<string>? ConnectionTestEntry { get; set; }

        [Input("crowdstrikeToken")]
        private Input<string>? _crowdstrikeToken;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: crowdstrike. Authentication token provided by Crowdstrike.
        /// </summary>
        public Input<string>? CrowdstrikeToken
        {
            get => _crowdstrikeToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _crowdstrikeToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination type: crowdstrike. Authentication token provided by Crowdstrike.
        /// </summary>
        [Input("crowdstrikeTokenMasked")]
        public Input<string>? CrowdstrikeTokenMasked { get; set; }

        [Input("datadogApiKey")]
        private Input<string>? _datadogApiKey;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: datadog. API key provided by Datadog.
        /// </summary>
        public Input<string>? DatadogApiKey
        {
            get => _datadogApiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _datadogApiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination type: datadog. API key provided by Datadog.
        /// </summary>
        [Input("datadogApiKeyMasked")]
        public Input<string>? DatadogApiKeyMasked { get; set; }

        /// <summary>
        /// Destination Type
        /// </summary>
        [Input("destinationType")]
        public Input<string>? DestinationType { get; set; }

        /// <summary>
        /// Destination Url
        /// </summary>
        [Input("destinationUrl")]
        public Input<string>? DestinationUrl { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("emailEntriesSent")]
        public Input<int>? EmailEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for email logs.
        /// </summary>
        [Input("emailSendEnabled")]
        public Input<bool>? EmailSendEnabled { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("exavaultApiRequestEntriesSent")]
        public Input<int>? ExavaultApiRequestEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" exavaultApiRequest " pulumi-lang-dotnet=" ExavaultApiRequest " pulumi-lang-go=" exavaultApiRequest " pulumi-lang-python=" exavault_api_request " pulumi-lang-yaml=" exavaultApiRequest " pulumi-lang-java=" exavaultApiRequest " pulumi-lang-hcl=" exavault_api_request "&gt; exavaultApiRequest &lt;/span&gt;logs.
        /// </summary>
        [Input("exavaultApiRequestSendEnabled")]
        public Input<bool>? ExavaultApiRequestSendEnabled { get; set; }

        /// <summary>
        /// Applicable only for destination type: file. Destination folder path on Files.com.
        /// </summary>
        [Input("fileDestinationPath")]
        public Input<string>? FileDestinationPath { get; set; }

        /// <summary>
        /// Applicable only for destination type: file. Generated file format.
        /// </summary>
        [Input("fileFormat")]
        public Input<string>? FileFormat { get; set; }

        /// <summary>
        /// Applicable only for destination type: file. Interval, in minutes, between file deliveries.
        /// </summary>
        [Input("fileIntervalMinutes")]
        public Input<int>? FileIntervalMinutes { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("ftpActionEntriesSent")]
        public Input<int>? FtpActionEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" ftpAction " pulumi-lang-dotnet=" FtpAction " pulumi-lang-go=" ftpAction " pulumi-lang-python=" ftp_action " pulumi-lang-yaml=" ftpAction " pulumi-lang-java=" ftpAction " pulumi-lang-hcl=" ftp_action "&gt; ftpAction &lt;/span&gt;logs.
        /// </summary>
        [Input("ftpActionSendEnabled")]
        public Input<bool>? FtpActionSendEnabled { get; set; }

        /// <summary>
        /// Applicable only for destination type: generic. Indicates the type of HTTP body. Can be&lt;span pulumi-lang-nodejs=" jsonNewline " pulumi-lang-dotnet=" JsonNewline " pulumi-lang-go=" jsonNewline " pulumi-lang-python=" json_newline " pulumi-lang-yaml=" jsonNewline " pulumi-lang-java=" jsonNewline " pulumi-lang-hcl=" json_newline "&gt; jsonNewline &lt;/span&gt;or json_array.&lt;span pulumi-lang-nodejs=" jsonNewline " pulumi-lang-dotnet=" JsonNewline " pulumi-lang-go=" jsonNewline " pulumi-lang-python=" json_newline " pulumi-lang-yaml=" jsonNewline " pulumi-lang-java=" jsonNewline " pulumi-lang-hcl=" json_newline "&gt; jsonNewline &lt;/span&gt;is multiple log entries as JSON separated by newlines.&lt;span pulumi-lang-nodejs=" jsonArray " pulumi-lang-dotnet=" JsonArray " pulumi-lang-go=" jsonArray " pulumi-lang-python=" json_array " pulumi-lang-yaml=" jsonArray " pulumi-lang-java=" jsonArray " pulumi-lang-hcl=" json_array "&gt; jsonArray &lt;/span&gt;is a single JSON array containing multiple log entries as JSON.
        /// </summary>
        [Input("genericPayloadType")]
        public Input<string>? GenericPayloadType { get; set; }

        /// <summary>
        /// Duration of the last HTTP Call in milliseconds
        /// </summary>
        [Input("lastHttpCallDurationMs")]
        public Input<int>? LastHttpCallDurationMs { get; set; }

        /// <summary>
        /// Last HTTP Call Error Message if applicable
        /// </summary>
        [Input("lastHttpCallErrorMessage")]
        public Input<string>? LastHttpCallErrorMessage { get; set; }

        /// <summary>
        /// Last HTTP Call Response Body. Large responses are truncated.
        /// </summary>
        [Input("lastHttpCallResponseBody")]
        public Input<string>? LastHttpCallResponseBody { get; set; }

        /// <summary>
        /// Last HTTP Call Response Code
        /// </summary>
        [Input("lastHttpCallResponseCode")]
        public Input<int>? LastHttpCallResponseCode { get; set; }

        /// <summary>
        /// Was the last HTTP call made successful?
        /// </summary>
        [Input("lastHttpCallSuccess")]
        public Input<bool>? LastHttpCallSuccess { get; set; }

        /// <summary>
        /// Type of URL that was last called. Can be &lt;span pulumi-lang-nodejs="`destinationUrl`" pulumi-lang-dotnet="`DestinationUrl`" pulumi-lang-go="`destinationUrl`" pulumi-lang-python="`destination_url`" pulumi-lang-yaml="`destinationUrl`" pulumi-lang-java="`destinationUrl`" pulumi-lang-hcl="`destination_url`"&gt;`destinationUrl`&lt;/span&gt; or &lt;span pulumi-lang-nodejs="`azureOauthClientCredentialsUrl`" pulumi-lang-dotnet="`AzureOauthClientCredentialsUrl`" pulumi-lang-go="`azureOauthClientCredentialsUrl`" pulumi-lang-python="`azure_oauth_client_credentials_url`" pulumi-lang-yaml="`azureOauthClientCredentialsUrl`" pulumi-lang-java="`azureOauthClientCredentialsUrl`" pulumi-lang-hcl="`azure_oauth_client_credentials_url`"&gt;`azureOauthClientCredentialsUrl`&lt;/span&gt;
        /// </summary>
        [Input("lastHttpCallTargetType")]
        public Input<string>? LastHttpCallTargetType { get; set; }

        /// <summary>
        /// Time of Last HTTP Call
        /// </summary>
        [Input("lastHttpCallTime")]
        public Input<string>? LastHttpCallTime { get; set; }

        /// <summary>
        /// Time of Most Recent Successful HTTP Call
        /// </summary>
        [Input("mostRecentHttpCallSuccessTime")]
        public Input<string>? MostRecentHttpCallSuccessTime { get; set; }

        /// <summary>
        /// Name for this Destination
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("newRelicApiKey")]
        private Input<string>? _newRelicApiKey;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: new_relic. API key provided by New Relic.
        /// </summary>
        public Input<string>? NewRelicApiKey
        {
            get => _newRelicApiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _newRelicApiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination type: new_relic. API key provided by New Relic.
        /// </summary>
        [Input("newRelicApiKeyMasked")]
        public Input<string>? NewRelicApiKeyMasked { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("outboundConnectionEntriesSent")]
        public Input<int>? OutboundConnectionEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" outboundConnection " pulumi-lang-dotnet=" OutboundConnection " pulumi-lang-go=" outboundConnection " pulumi-lang-python=" outbound_connection " pulumi-lang-yaml=" outboundConnection " pulumi-lang-java=" outboundConnection " pulumi-lang-hcl=" outbound_connection "&gt; outboundConnection &lt;/span&gt;logs.
        /// </summary>
        [Input("outboundConnectionSendEnabled")]
        public Input<bool>? OutboundConnectionSendEnabled { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("publicHostingRequestEntriesSent")]
        public Input<int>? PublicHostingRequestEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" publicHostingRequest " pulumi-lang-dotnet=" PublicHostingRequest " pulumi-lang-go=" publicHostingRequest " pulumi-lang-python=" public_hosting_request " pulumi-lang-yaml=" publicHostingRequest " pulumi-lang-java=" publicHostingRequest " pulumi-lang-hcl=" public_hosting_request "&gt; publicHostingRequest &lt;/span&gt;logs.
        /// </summary>
        [Input("publicHostingRequestSendEnabled")]
        public Input<bool>? PublicHostingRequestSendEnabled { get; set; }

        [Input("qradarPassword")]
        private Input<string>? _qradarPassword;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: qradar. Basic auth password provided by QRadar.
        /// </summary>
        public Input<string>? QradarPassword
        {
            get => _qradarPassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _qradarPassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination type: qradar. Basic auth password provided by QRadar.
        /// </summary>
        [Input("qradarPasswordMasked")]
        public Input<string>? QradarPasswordMasked { get; set; }

        /// <summary>
        /// Applicable only for destination type: qradar. Basic auth username provided by QRadar.
        /// </summary>
        [Input("qradarUsername")]
        public Input<string>? QradarUsername { get; set; }

        /// <summary>
        /// Whether this SIEM HTTP Destination is currently being sent to or not
        /// </summary>
        [Input("sendingActive")]
        public Input<bool>? SendingActive { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("settingsChangeEntriesSent")]
        public Input<int>? SettingsChangeEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" settingsChange " pulumi-lang-dotnet=" SettingsChange " pulumi-lang-go=" settingsChange " pulumi-lang-python=" settings_change " pulumi-lang-yaml=" settingsChange " pulumi-lang-java=" settingsChange " pulumi-lang-hcl=" settings_change "&gt; settingsChange &lt;/span&gt;logs.
        /// </summary>
        [Input("settingsChangeSendEnabled")]
        public Input<bool>? SettingsChangeSendEnabled { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("sftpActionEntriesSent")]
        public Input<int>? SftpActionEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" sftpAction " pulumi-lang-dotnet=" SftpAction " pulumi-lang-go=" sftpAction " pulumi-lang-python=" sftp_action " pulumi-lang-yaml=" sftpAction " pulumi-lang-java=" sftpAction " pulumi-lang-hcl=" sftp_action "&gt; sftpAction &lt;/span&gt;logs.
        /// </summary>
        [Input("sftpActionSendEnabled")]
        public Input<bool>? SftpActionSendEnabled { get; set; }

        [Input("solarWindsToken")]
        private Input<string>? _solarWindsToken;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination type: solar_winds. Authentication token provided by Solar Winds.
        /// </summary>
        public Input<string>? SolarWindsToken
        {
            get => _solarWindsToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _solarWindsToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination type: solar_winds. Authentication token provided by Solar Winds.
        /// </summary>
        [Input("solarWindsTokenMasked")]
        public Input<string>? SolarWindsTokenMasked { get; set; }

        [Input("splunkToken")]
        private Input<string>? _splunkToken;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Applicable only for destination types: splunk, splunk_compatible. Authentication token for the destination.
        /// </summary>
        public Input<string>? SplunkToken
        {
            get => _splunkToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _splunkToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Applicable only for destination types: splunk, splunk_compatible. Authentication token for the destination.
        /// </summary>
        [Input("splunkTokenMasked")]
        public Input<string>? SplunkTokenMasked { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("syncEntriesSent")]
        public Input<int>? SyncEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for sync logs.
        /// </summary>
        [Input("syncSendEnabled")]
        public Input<bool>? SyncSendEnabled { get; set; }

        /// <summary>
        /// Number of log entries sent for the lifetime of this destination.
        /// </summary>
        [Input("webDavActionEntriesSent")]
        public Input<int>? WebDavActionEntriesSent { get; set; }

        /// <summary>
        /// Whether or not sending is enabled for&lt;span pulumi-lang-nodejs=" webDavAction " pulumi-lang-dotnet=" WebDavAction " pulumi-lang-go=" webDavAction " pulumi-lang-python=" web_dav_action " pulumi-lang-yaml=" webDavAction " pulumi-lang-java=" webDavAction " pulumi-lang-hcl=" web_dav_action "&gt; webDavAction &lt;/span&gt;logs.
        /// </summary>
        [Input("webDavActionSendEnabled")]
        public Input<bool>? WebDavActionSendEnabled { get; set; }

        public SiemHttpDestinationState()
        {
        }
        public static new SiemHttpDestinationState Empty => new SiemHttpDestinationState();
    }
}
