# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetPaymentResult',
    'AwaitableGetPaymentResult',
    'get_payment',
    'get_payment_output',
]

@pulumi.output_type
class GetPaymentResult:
    """
    A collection of values returned by getPayment.
    """
    def __init__(__self__, amount=None, balance=None, created_at=None, currency=None, download_uri=None, id=None, invoice_line_items=None, method=None, payment_line_items=None, payment_reversed_at=None, payment_type=None, site_name=None, type=None):
        if amount and not isinstance(amount, str):
            raise TypeError("Expected argument 'amount' to be a str")
        pulumi.set(__self__, "amount", amount)
        if balance and not isinstance(balance, str):
            raise TypeError("Expected argument 'balance' to be a str")
        pulumi.set(__self__, "balance", balance)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if currency and not isinstance(currency, str):
            raise TypeError("Expected argument 'currency' to be a str")
        pulumi.set(__self__, "currency", currency)
        if download_uri and not isinstance(download_uri, str):
            raise TypeError("Expected argument 'download_uri' to be a str")
        pulumi.set(__self__, "download_uri", download_uri)
        if id and not isinstance(id, int):
            raise TypeError("Expected argument 'id' to be a int")
        pulumi.set(__self__, "id", id)
        if invoice_line_items and not isinstance(invoice_line_items, dict):
            raise TypeError("Expected argument 'invoice_line_items' to be a dict")
        pulumi.set(__self__, "invoice_line_items", invoice_line_items)
        if method and not isinstance(method, str):
            raise TypeError("Expected argument 'method' to be a str")
        pulumi.set(__self__, "method", method)
        if payment_line_items and not isinstance(payment_line_items, dict):
            raise TypeError("Expected argument 'payment_line_items' to be a dict")
        pulumi.set(__self__, "payment_line_items", payment_line_items)
        if payment_reversed_at and not isinstance(payment_reversed_at, str):
            raise TypeError("Expected argument 'payment_reversed_at' to be a str")
        pulumi.set(__self__, "payment_reversed_at", payment_reversed_at)
        if payment_type and not isinstance(payment_type, str):
            raise TypeError("Expected argument 'payment_type' to be a str")
        pulumi.set(__self__, "payment_type", payment_type)
        if site_name and not isinstance(site_name, str):
            raise TypeError("Expected argument 'site_name' to be a str")
        pulumi.set(__self__, "site_name", site_name)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def amount(self) -> _builtins.str:
        """
        Line item amount
        """
        return pulumi.get(self, "amount")

    @_builtins.property
    @pulumi.getter
    def balance(self) -> _builtins.str:
        """
        Line item balance
        """
        return pulumi.get(self, "balance")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        Line item created at
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def currency(self) -> _builtins.str:
        """
        Line item currency
        """
        return pulumi.get(self, "currency")

    @_builtins.property
    @pulumi.getter(name="downloadUri")
    def download_uri(self) -> _builtins.str:
        """
        Line item download uri
        """
        return pulumi.get(self, "download_uri")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.int:
        """
        Line item Id
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="invoiceLineItems")
    def invoice_line_items(self) -> Any:
        """
        Associated invoice line items
        """
        return pulumi.get(self, "invoice_line_items")

    @_builtins.property
    @pulumi.getter
    def method(self) -> _builtins.str:
        """
        Line item payment method
        """
        return pulumi.get(self, "method")

    @_builtins.property
    @pulumi.getter(name="paymentLineItems")
    def payment_line_items(self) -> Any:
        """
        Associated payment line items
        """
        return pulumi.get(self, "payment_line_items")

    @_builtins.property
    @pulumi.getter(name="paymentReversedAt")
    def payment_reversed_at(self) -> _builtins.str:
        """
        Date/time payment was reversed if applicable
        """
        return pulumi.get(self, "payment_reversed_at")

    @_builtins.property
    @pulumi.getter(name="paymentType")
    def payment_type(self) -> _builtins.str:
        """
        Type of payment if applicable
        """
        return pulumi.get(self, "payment_type")

    @_builtins.property
    @pulumi.getter(name="siteName")
    def site_name(self) -> _builtins.str:
        """
        Site name this line item is for
        """
        return pulumi.get(self, "site_name")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Type of line item, either payment or invoice
        """
        return pulumi.get(self, "type")


class AwaitableGetPaymentResult(GetPaymentResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPaymentResult(
            amount=self.amount,
            balance=self.balance,
            created_at=self.created_at,
            currency=self.currency,
            download_uri=self.download_uri,
            id=self.id,
            invoice_line_items=self.invoice_line_items,
            method=self.method,
            payment_line_items=self.payment_line_items,
            payment_reversed_at=self.payment_reversed_at,
            payment_type=self.payment_type,
            site_name=self.site_name,
            type=self.type)


def get_payment(id: Optional[_builtins.int] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPaymentResult:
    """
    An AccountLineItem is a single line item in the accounting ledger for a billing account. These include payments and invoices.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_payment = filescom.get_payment(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Line item Id
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('filescom:index/getPayment:getPayment', __args__, opts=opts, typ=GetPaymentResult).value

    return AwaitableGetPaymentResult(
        amount=pulumi.get(__ret__, 'amount'),
        balance=pulumi.get(__ret__, 'balance'),
        created_at=pulumi.get(__ret__, 'created_at'),
        currency=pulumi.get(__ret__, 'currency'),
        download_uri=pulumi.get(__ret__, 'download_uri'),
        id=pulumi.get(__ret__, 'id'),
        invoice_line_items=pulumi.get(__ret__, 'invoice_line_items'),
        method=pulumi.get(__ret__, 'method'),
        payment_line_items=pulumi.get(__ret__, 'payment_line_items'),
        payment_reversed_at=pulumi.get(__ret__, 'payment_reversed_at'),
        payment_type=pulumi.get(__ret__, 'payment_type'),
        site_name=pulumi.get(__ret__, 'site_name'),
        type=pulumi.get(__ret__, 'type'))
def get_payment_output(id: pulumi.Input[Optional[_builtins.int]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPaymentResult]:
    """
    An AccountLineItem is a single line item in the accounting ledger for a billing account. These include payments and invoices.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_payment = filescom.get_payment(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Line item Id
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('filescom:index/getPayment:getPayment', __args__, opts=opts, typ=GetPaymentResult)
    return __ret__.apply(lambda __response__: GetPaymentResult(
        amount=pulumi.get(__response__, 'amount'),
        balance=pulumi.get(__response__, 'balance'),
        created_at=pulumi.get(__response__, 'created_at'),
        currency=pulumi.get(__response__, 'currency'),
        download_uri=pulumi.get(__response__, 'download_uri'),
        id=pulumi.get(__response__, 'id'),
        invoice_line_items=pulumi.get(__response__, 'invoice_line_items'),
        method=pulumi.get(__response__, 'method'),
        payment_line_items=pulumi.get(__response__, 'payment_line_items'),
        payment_reversed_at=pulumi.get(__response__, 'payment_reversed_at'),
        payment_type=pulumi.get(__response__, 'payment_type'),
        site_name=pulumi.get(__response__, 'site_name'),
        type=pulumi.get(__response__, 'type')))
