# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetUserSecurityEventResult',
    'AwaitableGetUserSecurityEventResult',
    'get_user_security_event',
    'get_user_security_event_output',
]

@pulumi.output_type
class GetUserSecurityEventResult:
    """
    A collection of values returned by getUserSecurityEvent.
    """
    def __init__(__self__, body=None, body_url=None, created_at=None, event_errors=None, event_type=None, id=None, user_id=None):
        if body and not isinstance(body, str):
            raise TypeError("Expected argument 'body' to be a str")
        pulumi.set(__self__, "body", body)
        if body_url and not isinstance(body_url, str):
            raise TypeError("Expected argument 'body_url' to be a str")
        pulumi.set(__self__, "body_url", body_url)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if event_errors and not isinstance(event_errors, list):
            raise TypeError("Expected argument 'event_errors' to be a list")
        pulumi.set(__self__, "event_errors", event_errors)
        if event_type and not isinstance(event_type, str):
            raise TypeError("Expected argument 'event_type' to be a str")
        pulumi.set(__self__, "event_type", event_type)
        if id and not isinstance(id, int):
            raise TypeError("Expected argument 'id' to be a int")
        pulumi.set(__self__, "id", id)
        if user_id and not isinstance(user_id, int):
            raise TypeError("Expected argument 'user_id' to be a int")
        pulumi.set(__self__, "user_id", user_id)

    @_builtins.property
    @pulumi.getter
    def body(self) -> _builtins.str:
        """
        Event body.
        """
        return pulumi.get(self, "body")

    @_builtins.property
    @pulumi.getter(name="bodyUrl")
    def body_url(self) -> _builtins.str:
        """
        Link to log file.
        """
        return pulumi.get(self, "body_url")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        Event create date/time.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="eventErrors")
    def event_errors(self) -> Sequence[_builtins.str]:
        """
        Event errors.
        """
        return pulumi.get(self, "event_errors")

    @_builtins.property
    @pulumi.getter(name="eventType")
    def event_type(self) -> _builtins.str:
        """
        Type of user security event being recorded.
        """
        return pulumi.get(self, "event_type")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.int:
        """
        Event ID
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> _builtins.int:
        """
        User ID.
        """
        return pulumi.get(self, "user_id")


class AwaitableGetUserSecurityEventResult(GetUserSecurityEventResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetUserSecurityEventResult(
            body=self.body,
            body_url=self.body_url,
            created_at=self.created_at,
            event_errors=self.event_errors,
            event_type=self.event_type,
            id=self.id,
            user_id=self.user_id)


def get_user_security_event(id: Optional[_builtins.int] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetUserSecurityEventResult:
    """
    A UserSecurityEvent is a log record for user security activity such as user lockouts.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_user_security_event = filescom.get_user_security_event(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Event ID
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('filescom:index/getUserSecurityEvent:getUserSecurityEvent', __args__, opts=opts, typ=GetUserSecurityEventResult).value

    return AwaitableGetUserSecurityEventResult(
        body=pulumi.get(__ret__, 'body'),
        body_url=pulumi.get(__ret__, 'body_url'),
        created_at=pulumi.get(__ret__, 'created_at'),
        event_errors=pulumi.get(__ret__, 'event_errors'),
        event_type=pulumi.get(__ret__, 'event_type'),
        id=pulumi.get(__ret__, 'id'),
        user_id=pulumi.get(__ret__, 'user_id'))
def get_user_security_event_output(id: pulumi.Input[Optional[_builtins.int]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetUserSecurityEventResult]:
    """
    A UserSecurityEvent is a log record for user security activity such as user lockouts.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_user_security_event = filescom.get_user_security_event(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Event ID
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('filescom:index/getUserSecurityEvent:getUserSecurityEvent', __args__, opts=opts, typ=GetUserSecurityEventResult)
    return __ret__.apply(lambda __response__: GetUserSecurityEventResult(
        body=pulumi.get(__response__, 'body'),
        body_url=pulumi.get(__response__, 'body_url'),
        created_at=pulumi.get(__response__, 'created_at'),
        event_errors=pulumi.get(__response__, 'event_errors'),
        event_type=pulumi.get(__response__, 'event_type'),
        id=pulumi.get(__response__, 'id'),
        user_id=pulumi.get(__response__, 'user_id')))
