# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetMessageCommentReactionResult',
    'AwaitableGetMessageCommentReactionResult',
    'get_message_comment_reaction',
    'get_message_comment_reaction_output',
]

@pulumi.output_type
class GetMessageCommentReactionResult:
    """
    A collection of values returned by getMessageCommentReaction.
    """
    def __init__(__self__, emoji=None, id=None):
        if emoji and not isinstance(emoji, str):
            raise TypeError("Expected argument 'emoji' to be a str")
        pulumi.set(__self__, "emoji", emoji)
        if id and not isinstance(id, int):
            raise TypeError("Expected argument 'id' to be a int")
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def emoji(self) -> _builtins.str:
        """
        Emoji used in the reaction.
        """
        return pulumi.get(self, "emoji")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.int:
        """
        Reaction ID
        """
        return pulumi.get(self, "id")


class AwaitableGetMessageCommentReactionResult(GetMessageCommentReactionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMessageCommentReactionResult(
            emoji=self.emoji,
            id=self.id)


def get_message_comment_reaction(id: Optional[_builtins.int] = None,
                                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMessageCommentReactionResult:
    """
    A MessageCommentReaction is a reaction emoji made by a user on a message comment.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_message_comment_reaction = filescom.get_message_comment_reaction(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Reaction ID
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('filescom:index/getMessageCommentReaction:getMessageCommentReaction', __args__, opts=opts, typ=GetMessageCommentReactionResult).value

    return AwaitableGetMessageCommentReactionResult(
        emoji=pulumi.get(__ret__, 'emoji'),
        id=pulumi.get(__ret__, 'id'))
def get_message_comment_reaction_output(id: pulumi.Input[Optional[_builtins.int]] = None,
                                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMessageCommentReactionResult]:
    """
    A MessageCommentReaction is a reaction emoji made by a user on a message comment.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_message_comment_reaction = filescom.get_message_comment_reaction(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Reaction ID
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('filescom:index/getMessageCommentReaction:getMessageCommentReaction', __args__, opts=opts, typ=GetMessageCommentReactionResult)
    return __ret__.apply(lambda __response__: GetMessageCommentReactionResult(
        emoji=pulumi.get(__response__, 'emoji'),
        id=pulumi.get(__response__, 'id')))
