# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetGroupResult',
    'AwaitableGetGroupResult',
    'get_group',
    'get_group_output',
]

@pulumi.output_type
class GetGroupResult:
    """
    A collection of values returned by getGroup.
    """
    def __init__(__self__, admin_ids=None, ai_assistant_personality_id=None, allowed_ips=None, dav_permission=None, desktop_configuration_profile_id=None, ftp_permission=None, id=None, integration_centric_profile_id=None, name=None, notes=None, restapi_permission=None, sftp_permission=None, site_id=None, user_ids=None, usernames=None, workspace_id=None):
        if admin_ids and not isinstance(admin_ids, str):
            raise TypeError("Expected argument 'admin_ids' to be a str")
        pulumi.set(__self__, "admin_ids", admin_ids)
        if ai_assistant_personality_id and not isinstance(ai_assistant_personality_id, int):
            raise TypeError("Expected argument 'ai_assistant_personality_id' to be a int")
        pulumi.set(__self__, "ai_assistant_personality_id", ai_assistant_personality_id)
        if allowed_ips and not isinstance(allowed_ips, str):
            raise TypeError("Expected argument 'allowed_ips' to be a str")
        pulumi.set(__self__, "allowed_ips", allowed_ips)
        if dav_permission and not isinstance(dav_permission, bool):
            raise TypeError("Expected argument 'dav_permission' to be a bool")
        pulumi.set(__self__, "dav_permission", dav_permission)
        if desktop_configuration_profile_id and not isinstance(desktop_configuration_profile_id, int):
            raise TypeError("Expected argument 'desktop_configuration_profile_id' to be a int")
        pulumi.set(__self__, "desktop_configuration_profile_id", desktop_configuration_profile_id)
        if ftp_permission and not isinstance(ftp_permission, bool):
            raise TypeError("Expected argument 'ftp_permission' to be a bool")
        pulumi.set(__self__, "ftp_permission", ftp_permission)
        if id and not isinstance(id, int):
            raise TypeError("Expected argument 'id' to be a int")
        pulumi.set(__self__, "id", id)
        if integration_centric_profile_id and not isinstance(integration_centric_profile_id, int):
            raise TypeError("Expected argument 'integration_centric_profile_id' to be a int")
        pulumi.set(__self__, "integration_centric_profile_id", integration_centric_profile_id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if notes and not isinstance(notes, str):
            raise TypeError("Expected argument 'notes' to be a str")
        pulumi.set(__self__, "notes", notes)
        if restapi_permission and not isinstance(restapi_permission, bool):
            raise TypeError("Expected argument 'restapi_permission' to be a bool")
        pulumi.set(__self__, "restapi_permission", restapi_permission)
        if sftp_permission and not isinstance(sftp_permission, bool):
            raise TypeError("Expected argument 'sftp_permission' to be a bool")
        pulumi.set(__self__, "sftp_permission", sftp_permission)
        if site_id and not isinstance(site_id, int):
            raise TypeError("Expected argument 'site_id' to be a int")
        pulumi.set(__self__, "site_id", site_id)
        if user_ids and not isinstance(user_ids, str):
            raise TypeError("Expected argument 'user_ids' to be a str")
        pulumi.set(__self__, "user_ids", user_ids)
        if usernames and not isinstance(usernames, str):
            raise TypeError("Expected argument 'usernames' to be a str")
        pulumi.set(__self__, "usernames", usernames)
        if workspace_id and not isinstance(workspace_id, int):
            raise TypeError("Expected argument 'workspace_id' to be a int")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="adminIds")
    def admin_ids(self) -> _builtins.str:
        """
        Comma-delimited list of user IDs who are group administrators (separated by commas)
        """
        return pulumi.get(self, "admin_ids")

    @_builtins.property
    @pulumi.getter(name="aiAssistantPersonalityId")
    def ai_assistant_personality_id(self) -> _builtins.int:
        """
        AI Assistant Personality ID assigned to this Group, if any. Users in the Group inherit it unless a direct per-user or Partner assignment overrides it.
        """
        return pulumi.get(self, "ai_assistant_personality_id")

    @_builtins.property
    @pulumi.getter(name="allowedIps")
    def allowed_ips(self) -> _builtins.str:
        """
        A list of allowed IPs if applicable.  Newline delimited
        """
        return pulumi.get(self, "allowed_ips")

    @_builtins.property
    @pulumi.getter(name="davPermission")
    def dav_permission(self) -> _builtins.bool:
        """
        If true, users in this group can use WebDAV to login.  This will override a false value of <span pulumi-lang-nodejs="`davPermission`" pulumi-lang-dotnet="`DavPermission`" pulumi-lang-go="`davPermission`" pulumi-lang-python="`dav_permission`" pulumi-lang-yaml="`davPermission`" pulumi-lang-java="`davPermission`" pulumi-lang-hcl="`dav_permission`">`davPermission`</span> on the user level.
        """
        return pulumi.get(self, "dav_permission")

    @_builtins.property
    @pulumi.getter(name="desktopConfigurationProfileId")
    def desktop_configuration_profile_id(self) -> _builtins.int:
        """
        Desktop Configuration Profile ID assigned to this Group, if any. Users in the Group inherit it unless a direct per-user assignment overrides it.
        """
        return pulumi.get(self, "desktop_configuration_profile_id")

    @_builtins.property
    @pulumi.getter(name="ftpPermission")
    def ftp_permission(self) -> _builtins.bool:
        """
        If true, users in this group can use FTP to login.  This will override a false value of <span pulumi-lang-nodejs="`ftpPermission`" pulumi-lang-dotnet="`FtpPermission`" pulumi-lang-go="`ftpPermission`" pulumi-lang-python="`ftp_permission`" pulumi-lang-yaml="`ftpPermission`" pulumi-lang-java="`ftpPermission`" pulumi-lang-hcl="`ftp_permission`">`ftpPermission`</span> on the user level.
        """
        return pulumi.get(self, "ftp_permission")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.int:
        """
        Group ID
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="integrationCentricProfileId")
    def integration_centric_profile_id(self) -> _builtins.int:
        """
        Integration Centric Profile ID assigned to this Group, if any. Users in the Group inherit it unless a direct per-user assignment overrides it.
        """
        return pulumi.get(self, "integration_centric_profile_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Group name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def notes(self) -> _builtins.str:
        """
        Notes about this group
        """
        return pulumi.get(self, "notes")

    @_builtins.property
    @pulumi.getter(name="restapiPermission")
    def restapi_permission(self) -> _builtins.bool:
        """
        If true, users in this group can use the REST API to login.  This will override a false value of <span pulumi-lang-nodejs="`restapiPermission`" pulumi-lang-dotnet="`RestapiPermission`" pulumi-lang-go="`restapiPermission`" pulumi-lang-python="`restapi_permission`" pulumi-lang-yaml="`restapiPermission`" pulumi-lang-java="`restapiPermission`" pulumi-lang-hcl="`restapi_permission`">`restapiPermission`</span> on the user level.
        """
        return pulumi.get(self, "restapi_permission")

    @_builtins.property
    @pulumi.getter(name="sftpPermission")
    def sftp_permission(self) -> _builtins.bool:
        """
        If true, users in this group can use SFTP to login.  This will override a false value of <span pulumi-lang-nodejs="`sftpPermission`" pulumi-lang-dotnet="`SftpPermission`" pulumi-lang-go="`sftpPermission`" pulumi-lang-python="`sftp_permission`" pulumi-lang-yaml="`sftpPermission`" pulumi-lang-java="`sftpPermission`" pulumi-lang-hcl="`sftp_permission`">`sftpPermission`</span> on the user level.
        """
        return pulumi.get(self, "sftp_permission")

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> _builtins.int:
        """
        Site ID
        """
        return pulumi.get(self, "site_id")

    @_builtins.property
    @pulumi.getter(name="userIds")
    def user_ids(self) -> _builtins.str:
        """
        Comma-delimited list of user IDs who belong to this group (separated by commas)
        """
        return pulumi.get(self, "user_ids")

    @_builtins.property
    @pulumi.getter
    def usernames(self) -> _builtins.str:
        """
        Comma-delimited list of usernames who belong to this group (separated by commas)
        """
        return pulumi.get(self, "usernames")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> _builtins.int:
        """
        Workspace ID
        """
        return pulumi.get(self, "workspace_id")


class AwaitableGetGroupResult(GetGroupResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGroupResult(
            admin_ids=self.admin_ids,
            ai_assistant_personality_id=self.ai_assistant_personality_id,
            allowed_ips=self.allowed_ips,
            dav_permission=self.dav_permission,
            desktop_configuration_profile_id=self.desktop_configuration_profile_id,
            ftp_permission=self.ftp_permission,
            id=self.id,
            integration_centric_profile_id=self.integration_centric_profile_id,
            name=self.name,
            notes=self.notes,
            restapi_permission=self.restapi_permission,
            sftp_permission=self.sftp_permission,
            site_id=self.site_id,
            user_ids=self.user_ids,
            usernames=self.usernames,
            workspace_id=self.workspace_id)


def get_group(id: Optional[_builtins.int] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGroupResult:
    """
    A Group is a powerful tool for permissions and user management on Files.com. Users can belong to multiple groups.

    All permissions can be managed via Groups, and Groups can also be synced to your identity platform via LDAP or SCIM.

    Files.com's Group Admin feature allows you to define Group Admins, who then have access to add and remove users within their groups.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_group = filescom.get_group(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Group ID
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('filescom:index/getGroup:getGroup', __args__, opts=opts, typ=GetGroupResult).value

    return AwaitableGetGroupResult(
        admin_ids=pulumi.get(__ret__, 'admin_ids'),
        ai_assistant_personality_id=pulumi.get(__ret__, 'ai_assistant_personality_id'),
        allowed_ips=pulumi.get(__ret__, 'allowed_ips'),
        dav_permission=pulumi.get(__ret__, 'dav_permission'),
        desktop_configuration_profile_id=pulumi.get(__ret__, 'desktop_configuration_profile_id'),
        ftp_permission=pulumi.get(__ret__, 'ftp_permission'),
        id=pulumi.get(__ret__, 'id'),
        integration_centric_profile_id=pulumi.get(__ret__, 'integration_centric_profile_id'),
        name=pulumi.get(__ret__, 'name'),
        notes=pulumi.get(__ret__, 'notes'),
        restapi_permission=pulumi.get(__ret__, 'restapi_permission'),
        sftp_permission=pulumi.get(__ret__, 'sftp_permission'),
        site_id=pulumi.get(__ret__, 'site_id'),
        user_ids=pulumi.get(__ret__, 'user_ids'),
        usernames=pulumi.get(__ret__, 'usernames'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_group_output(id: pulumi.Input[Optional[_builtins.int]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGroupResult]:
    """
    A Group is a powerful tool for permissions and user management on Files.com. Users can belong to multiple groups.

    All permissions can be managed via Groups, and Groups can also be synced to your identity platform via LDAP or SCIM.

    Files.com's Group Admin feature allows you to define Group Admins, who then have access to add and remove users within their groups.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_group = filescom.get_group(id=1)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.int id: Group ID
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('filescom:index/getGroup:getGroup', __args__, opts=opts, typ=GetGroupResult)
    return __ret__.apply(lambda __response__: GetGroupResult(
        admin_ids=pulumi.get(__response__, 'admin_ids'),
        ai_assistant_personality_id=pulumi.get(__response__, 'ai_assistant_personality_id'),
        allowed_ips=pulumi.get(__response__, 'allowed_ips'),
        dav_permission=pulumi.get(__response__, 'dav_permission'),
        desktop_configuration_profile_id=pulumi.get(__response__, 'desktop_configuration_profile_id'),
        ftp_permission=pulumi.get(__response__, 'ftp_permission'),
        id=pulumi.get(__response__, 'id'),
        integration_centric_profile_id=pulumi.get(__response__, 'integration_centric_profile_id'),
        name=pulumi.get(__response__, 'name'),
        notes=pulumi.get(__response__, 'notes'),
        restapi_permission=pulumi.get(__response__, 'restapi_permission'),
        sftp_permission=pulumi.get(__response__, 'sftp_permission'),
        site_id=pulumi.get(__response__, 'site_id'),
        user_ids=pulumi.get(__response__, 'user_ids'),
        usernames=pulumi.get(__response__, 'usernames'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
