# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetFolderResult',
    'AwaitableGetFolderResult',
    'get_folder',
    'get_folder_output',
]

@pulumi.output_type
class GetFolderResult:
    """
    A collection of values returned by getFolder.
    """
    def __init__(__self__, crc32=None, created_at=None, created_by_api_key_id=None, created_by_as2_incoming_message_id=None, created_by_automation_id=None, created_by_bundle_registration_id=None, created_by_id=None, created_by_inbox_id=None, created_by_remote_server_id=None, created_by_sync_id=None, custom_metadata=None, direct_connection_info=None, display_name=None, download_uri=None, is_locked=None, last_modified_by_api_key_id=None, last_modified_by_automation_id=None, last_modified_by_bundle_registration_id=None, last_modified_by_id=None, last_modified_by_remote_server_id=None, last_modified_by_sync_id=None, md5=None, mime_type=None, mtime=None, path=None, permissions=None, preview=None, preview_id=None, priority_color=None, provided_mtime=None, region=None, sha1=None, sha256=None, size=None, subfolders_locked=None, type=None):
        if crc32 and not isinstance(crc32, str):
            raise TypeError("Expected argument 'crc32' to be a str")
        pulumi.set(__self__, "crc32", crc32)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if created_by_api_key_id and not isinstance(created_by_api_key_id, int):
            raise TypeError("Expected argument 'created_by_api_key_id' to be a int")
        pulumi.set(__self__, "created_by_api_key_id", created_by_api_key_id)
        if created_by_as2_incoming_message_id and not isinstance(created_by_as2_incoming_message_id, int):
            raise TypeError("Expected argument 'created_by_as2_incoming_message_id' to be a int")
        pulumi.set(__self__, "created_by_as2_incoming_message_id", created_by_as2_incoming_message_id)
        if created_by_automation_id and not isinstance(created_by_automation_id, int):
            raise TypeError("Expected argument 'created_by_automation_id' to be a int")
        pulumi.set(__self__, "created_by_automation_id", created_by_automation_id)
        if created_by_bundle_registration_id and not isinstance(created_by_bundle_registration_id, int):
            raise TypeError("Expected argument 'created_by_bundle_registration_id' to be a int")
        pulumi.set(__self__, "created_by_bundle_registration_id", created_by_bundle_registration_id)
        if created_by_id and not isinstance(created_by_id, int):
            raise TypeError("Expected argument 'created_by_id' to be a int")
        pulumi.set(__self__, "created_by_id", created_by_id)
        if created_by_inbox_id and not isinstance(created_by_inbox_id, int):
            raise TypeError("Expected argument 'created_by_inbox_id' to be a int")
        pulumi.set(__self__, "created_by_inbox_id", created_by_inbox_id)
        if created_by_remote_server_id and not isinstance(created_by_remote_server_id, int):
            raise TypeError("Expected argument 'created_by_remote_server_id' to be a int")
        pulumi.set(__self__, "created_by_remote_server_id", created_by_remote_server_id)
        if created_by_sync_id and not isinstance(created_by_sync_id, int):
            raise TypeError("Expected argument 'created_by_sync_id' to be a int")
        pulumi.set(__self__, "created_by_sync_id", created_by_sync_id)
        if custom_metadata and not isinstance(custom_metadata, dict):
            raise TypeError("Expected argument 'custom_metadata' to be a dict")
        pulumi.set(__self__, "custom_metadata", custom_metadata)
        if direct_connection_info and not isinstance(direct_connection_info, str):
            raise TypeError("Expected argument 'direct_connection_info' to be a str")
        pulumi.set(__self__, "direct_connection_info", direct_connection_info)
        if display_name and not isinstance(display_name, str):
            raise TypeError("Expected argument 'display_name' to be a str")
        pulumi.set(__self__, "display_name", display_name)
        if download_uri and not isinstance(download_uri, str):
            raise TypeError("Expected argument 'download_uri' to be a str")
        pulumi.set(__self__, "download_uri", download_uri)
        if is_locked and not isinstance(is_locked, bool):
            raise TypeError("Expected argument 'is_locked' to be a bool")
        pulumi.set(__self__, "is_locked", is_locked)
        if last_modified_by_api_key_id and not isinstance(last_modified_by_api_key_id, int):
            raise TypeError("Expected argument 'last_modified_by_api_key_id' to be a int")
        pulumi.set(__self__, "last_modified_by_api_key_id", last_modified_by_api_key_id)
        if last_modified_by_automation_id and not isinstance(last_modified_by_automation_id, int):
            raise TypeError("Expected argument 'last_modified_by_automation_id' to be a int")
        pulumi.set(__self__, "last_modified_by_automation_id", last_modified_by_automation_id)
        if last_modified_by_bundle_registration_id and not isinstance(last_modified_by_bundle_registration_id, int):
            raise TypeError("Expected argument 'last_modified_by_bundle_registration_id' to be a int")
        pulumi.set(__self__, "last_modified_by_bundle_registration_id", last_modified_by_bundle_registration_id)
        if last_modified_by_id and not isinstance(last_modified_by_id, int):
            raise TypeError("Expected argument 'last_modified_by_id' to be a int")
        pulumi.set(__self__, "last_modified_by_id", last_modified_by_id)
        if last_modified_by_remote_server_id and not isinstance(last_modified_by_remote_server_id, int):
            raise TypeError("Expected argument 'last_modified_by_remote_server_id' to be a int")
        pulumi.set(__self__, "last_modified_by_remote_server_id", last_modified_by_remote_server_id)
        if last_modified_by_sync_id and not isinstance(last_modified_by_sync_id, int):
            raise TypeError("Expected argument 'last_modified_by_sync_id' to be a int")
        pulumi.set(__self__, "last_modified_by_sync_id", last_modified_by_sync_id)
        if md5 and not isinstance(md5, str):
            raise TypeError("Expected argument 'md5' to be a str")
        pulumi.set(__self__, "md5", md5)
        if mime_type and not isinstance(mime_type, str):
            raise TypeError("Expected argument 'mime_type' to be a str")
        pulumi.set(__self__, "mime_type", mime_type)
        if mtime and not isinstance(mtime, str):
            raise TypeError("Expected argument 'mtime' to be a str")
        pulumi.set(__self__, "mtime", mtime)
        if path and not isinstance(path, str):
            raise TypeError("Expected argument 'path' to be a str")
        pulumi.set(__self__, "path", path)
        if permissions and not isinstance(permissions, str):
            raise TypeError("Expected argument 'permissions' to be a str")
        pulumi.set(__self__, "permissions", permissions)
        if preview and not isinstance(preview, str):
            raise TypeError("Expected argument 'preview' to be a str")
        pulumi.set(__self__, "preview", preview)
        if preview_id and not isinstance(preview_id, int):
            raise TypeError("Expected argument 'preview_id' to be a int")
        pulumi.set(__self__, "preview_id", preview_id)
        if priority_color and not isinstance(priority_color, str):
            raise TypeError("Expected argument 'priority_color' to be a str")
        pulumi.set(__self__, "priority_color", priority_color)
        if provided_mtime and not isinstance(provided_mtime, str):
            raise TypeError("Expected argument 'provided_mtime' to be a str")
        pulumi.set(__self__, "provided_mtime", provided_mtime)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if sha1 and not isinstance(sha1, str):
            raise TypeError("Expected argument 'sha1' to be a str")
        pulumi.set(__self__, "sha1", sha1)
        if sha256 and not isinstance(sha256, str):
            raise TypeError("Expected argument 'sha256' to be a str")
        pulumi.set(__self__, "sha256", sha256)
        if size and not isinstance(size, int):
            raise TypeError("Expected argument 'size' to be a int")
        pulumi.set(__self__, "size", size)
        if subfolders_locked and not isinstance(subfolders_locked, bool):
            raise TypeError("Expected argument 'subfolders_locked' to be a bool")
        pulumi.set(__self__, "subfolders_locked", subfolders_locked)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def crc32(self) -> _builtins.str:
        """
        File CRC32 checksum. This is sometimes delayed, so if you get a blank response, wait and try again.
        """
        return pulumi.get(self, "crc32")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        File created date/time
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="createdByApiKeyId")
    def created_by_api_key_id(self) -> _builtins.int:
        """
        ID of the API key that created the file/folder
        """
        return pulumi.get(self, "created_by_api_key_id")

    @_builtins.property
    @pulumi.getter(name="createdByAs2IncomingMessageId")
    def created_by_as2_incoming_message_id(self) -> _builtins.int:
        """
        ID of the AS2 Incoming Message that created the file/folder
        """
        return pulumi.get(self, "created_by_as2_incoming_message_id")

    @_builtins.property
    @pulumi.getter(name="createdByAutomationId")
    def created_by_automation_id(self) -> _builtins.int:
        """
        ID of the Automation that created the file/folder
        """
        return pulumi.get(self, "created_by_automation_id")

    @_builtins.property
    @pulumi.getter(name="createdByBundleRegistrationId")
    def created_by_bundle_registration_id(self) -> _builtins.int:
        """
        ID of the Bundle Registration that created the file/folder
        """
        return pulumi.get(self, "created_by_bundle_registration_id")

    @_builtins.property
    @pulumi.getter(name="createdById")
    def created_by_id(self) -> _builtins.int:
        """
        User ID of the User who created the file/folder
        """
        return pulumi.get(self, "created_by_id")

    @_builtins.property
    @pulumi.getter(name="createdByInboxId")
    def created_by_inbox_id(self) -> _builtins.int:
        """
        ID of the Inbox that created the file/folder
        """
        return pulumi.get(self, "created_by_inbox_id")

    @_builtins.property
    @pulumi.getter(name="createdByRemoteServerId")
    def created_by_remote_server_id(self) -> _builtins.int:
        """
        ID of the Remote Server that created the file/folder
        """
        return pulumi.get(self, "created_by_remote_server_id")

    @_builtins.property
    @pulumi.getter(name="createdBySyncId")
    def created_by_sync_id(self) -> _builtins.int:
        """
        ID of the Sync that created the file/folder
        """
        return pulumi.get(self, "created_by_sync_id")

    @_builtins.property
    @pulumi.getter(name="customMetadata")
    def custom_metadata(self) -> Any:
        """
        Custom metadata map of keys and values. Limited to 32 keys, 256 characters per key and 1024 characters per value.
        """
        return pulumi.get(self, "custom_metadata")

    @_builtins.property
    @pulumi.getter(name="directConnectionInfo")
    def direct_connection_info(self) -> _builtins.str:
        """
        Optional direct connection information for direct Agent transfer attempts
        """
        return pulumi.get(self, "direct_connection_info")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> _builtins.str:
        """
        File/Folder display name
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="downloadUri")
    def download_uri(self) -> _builtins.str:
        """
        Link to download file. Provided only in response to a download request.
        """
        return pulumi.get(self, "download_uri")

    @_builtins.property
    @pulumi.getter(name="isLocked")
    def is_locked(self) -> _builtins.bool:
        """
        Is this folder locked and unable to be modified?
        """
        return pulumi.get(self, "is_locked")

    @_builtins.property
    @pulumi.getter(name="lastModifiedByApiKeyId")
    def last_modified_by_api_key_id(self) -> _builtins.int:
        """
        ID of the API key that last modified the file/folder
        """
        return pulumi.get(self, "last_modified_by_api_key_id")

    @_builtins.property
    @pulumi.getter(name="lastModifiedByAutomationId")
    def last_modified_by_automation_id(self) -> _builtins.int:
        """
        ID of the Automation that last modified the file/folder
        """
        return pulumi.get(self, "last_modified_by_automation_id")

    @_builtins.property
    @pulumi.getter(name="lastModifiedByBundleRegistrationId")
    def last_modified_by_bundle_registration_id(self) -> _builtins.int:
        """
        ID of the Bundle Registration that last modified the file/folder
        """
        return pulumi.get(self, "last_modified_by_bundle_registration_id")

    @_builtins.property
    @pulumi.getter(name="lastModifiedById")
    def last_modified_by_id(self) -> _builtins.int:
        """
        User ID of the User who last modified the file/folder
        """
        return pulumi.get(self, "last_modified_by_id")

    @_builtins.property
    @pulumi.getter(name="lastModifiedByRemoteServerId")
    def last_modified_by_remote_server_id(self) -> _builtins.int:
        """
        ID of the Remote Server that last modified the file/folder
        """
        return pulumi.get(self, "last_modified_by_remote_server_id")

    @_builtins.property
    @pulumi.getter(name="lastModifiedBySyncId")
    def last_modified_by_sync_id(self) -> _builtins.int:
        """
        ID of the Sync that last modified the file/folder
        """
        return pulumi.get(self, "last_modified_by_sync_id")

    @_builtins.property
    @pulumi.getter
    def md5(self) -> _builtins.str:
        """
        File MD5 checksum. This is sometimes delayed, so if you get a blank response, wait and try again.
        """
        return pulumi.get(self, "md5")

    @_builtins.property
    @pulumi.getter(name="mimeType")
    def mime_type(self) -> _builtins.str:
        """
        MIME Type.  This is determined by the filename extension and is not stored separately internally.
        """
        return pulumi.get(self, "mime_type")

    @_builtins.property
    @pulumi.getter
    def mtime(self) -> _builtins.str:
        """
        File last modified date/time, according to the server.  This is the timestamp of the last Files.com operation of the file, regardless of what modified timestamp was sent.
        """
        return pulumi.get(self, "mtime")

    @_builtins.property
    @pulumi.getter
    def path(self) -> _builtins.str:
        """
        File/Folder path. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.
        """
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> _builtins.str:
        """
        A short string representing the current user's permissions.  Can be <span pulumi-lang-nodejs="`r`" pulumi-lang-dotnet="`R`" pulumi-lang-go="`r`" pulumi-lang-python="`r`" pulumi-lang-yaml="`r`" pulumi-lang-java="`r`" pulumi-lang-hcl="`r`">`r`</span> (Read),<span pulumi-lang-nodejs="`w`" pulumi-lang-dotnet="`W`" pulumi-lang-go="`w`" pulumi-lang-python="`w`" pulumi-lang-yaml="`w`" pulumi-lang-java="`w`" pulumi-lang-hcl="`w`">`w`</span> (Write),<span pulumi-lang-nodejs="`d`" pulumi-lang-dotnet="`D`" pulumi-lang-go="`d`" pulumi-lang-python="`d`" pulumi-lang-yaml="`d`" pulumi-lang-java="`d`" pulumi-lang-hcl="`d`">`d`</span> (Delete), <span pulumi-lang-nodejs="`l`" pulumi-lang-dotnet="`L`" pulumi-lang-go="`l`" pulumi-lang-python="`l`" pulumi-lang-yaml="`l`" pulumi-lang-java="`l`" pulumi-lang-hcl="`l`">`l`</span> (List) or any combination
        """
        return pulumi.get(self, "permissions")

    @_builtins.property
    @pulumi.getter
    def preview(self) -> _builtins.str:
        """
        File preview
        """
        return pulumi.get(self, "preview")

    @_builtins.property
    @pulumi.getter(name="previewId")
    def preview_id(self) -> _builtins.int:
        """
        File preview ID
        """
        return pulumi.get(self, "preview_id")

    @_builtins.property
    @pulumi.getter(name="priorityColor")
    def priority_color(self) -> _builtins.str:
        """
        Bookmark/priority color of file/folder
        """
        return pulumi.get(self, "priority_color")

    @_builtins.property
    @pulumi.getter(name="providedMtime")
    def provided_mtime(self) -> _builtins.str:
        """
        File last modified date/time, according to the client who set it.  Files.com allows desktop, FTP, SFTP, and WebDAV clients to set modified at times.  This allows Desktop<->Cloud syncing to preserve modified at times.
        """
        return pulumi.get(self, "provided_mtime")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        """
        Region location
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def sha1(self) -> _builtins.str:
        """
        File SHA1 checksum. This is sometimes delayed, so if you get a blank response, wait and try again.
        """
        return pulumi.get(self, "sha1")

    @_builtins.property
    @pulumi.getter
    def sha256(self) -> _builtins.str:
        """
        File SHA256 checksum. This is sometimes delayed, so if you get a blank response, wait and try again.
        """
        return pulumi.get(self, "sha256")

    @_builtins.property
    @pulumi.getter
    def size(self) -> _builtins.int:
        """
        File/Folder size
        """
        return pulumi.get(self, "size")

    @_builtins.property
    @pulumi.getter(name="subfoldersLocked")
    def subfolders_locked(self) -> _builtins.bool:
        """
        Are subfolders locked and unable to be modified?
        """
        return pulumi.get(self, "subfolders_locked")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Type: <span pulumi-lang-nodejs="`directory`" pulumi-lang-dotnet="`Directory`" pulumi-lang-go="`directory`" pulumi-lang-python="`directory`" pulumi-lang-yaml="`directory`" pulumi-lang-java="`directory`" pulumi-lang-hcl="`directory`">`directory`</span> or <span pulumi-lang-nodejs="`file`" pulumi-lang-dotnet="`File`" pulumi-lang-go="`file`" pulumi-lang-python="`file`" pulumi-lang-yaml="`file`" pulumi-lang-java="`file`" pulumi-lang-hcl="`file`">`file`</span>.
        """
        return pulumi.get(self, "type")


class AwaitableGetFolderResult(GetFolderResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetFolderResult(
            crc32=self.crc32,
            created_at=self.created_at,
            created_by_api_key_id=self.created_by_api_key_id,
            created_by_as2_incoming_message_id=self.created_by_as2_incoming_message_id,
            created_by_automation_id=self.created_by_automation_id,
            created_by_bundle_registration_id=self.created_by_bundle_registration_id,
            created_by_id=self.created_by_id,
            created_by_inbox_id=self.created_by_inbox_id,
            created_by_remote_server_id=self.created_by_remote_server_id,
            created_by_sync_id=self.created_by_sync_id,
            custom_metadata=self.custom_metadata,
            direct_connection_info=self.direct_connection_info,
            display_name=self.display_name,
            download_uri=self.download_uri,
            is_locked=self.is_locked,
            last_modified_by_api_key_id=self.last_modified_by_api_key_id,
            last_modified_by_automation_id=self.last_modified_by_automation_id,
            last_modified_by_bundle_registration_id=self.last_modified_by_bundle_registration_id,
            last_modified_by_id=self.last_modified_by_id,
            last_modified_by_remote_server_id=self.last_modified_by_remote_server_id,
            last_modified_by_sync_id=self.last_modified_by_sync_id,
            md5=self.md5,
            mime_type=self.mime_type,
            mtime=self.mtime,
            path=self.path,
            permissions=self.permissions,
            preview=self.preview,
            preview_id=self.preview_id,
            priority_color=self.priority_color,
            provided_mtime=self.provided_mtime,
            region=self.region,
            sha1=self.sha1,
            sha256=self.sha256,
            size=self.size,
            subfolders_locked=self.subfolders_locked,
            type=self.type)


def get_folder(path: Optional[_builtins.str] = None,
               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetFolderResult:
    """
    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_folder = filescom.get_folder(path="path")
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.str path: File/Folder path. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.
    """
    __args__ = dict()
    __args__['path'] = path
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('filescom:index/getFolder:getFolder', __args__, opts=opts, typ=GetFolderResult).value

    return AwaitableGetFolderResult(
        crc32=pulumi.get(__ret__, 'crc32'),
        created_at=pulumi.get(__ret__, 'created_at'),
        created_by_api_key_id=pulumi.get(__ret__, 'created_by_api_key_id'),
        created_by_as2_incoming_message_id=pulumi.get(__ret__, 'created_by_as2_incoming_message_id'),
        created_by_automation_id=pulumi.get(__ret__, 'created_by_automation_id'),
        created_by_bundle_registration_id=pulumi.get(__ret__, 'created_by_bundle_registration_id'),
        created_by_id=pulumi.get(__ret__, 'created_by_id'),
        created_by_inbox_id=pulumi.get(__ret__, 'created_by_inbox_id'),
        created_by_remote_server_id=pulumi.get(__ret__, 'created_by_remote_server_id'),
        created_by_sync_id=pulumi.get(__ret__, 'created_by_sync_id'),
        custom_metadata=pulumi.get(__ret__, 'custom_metadata'),
        direct_connection_info=pulumi.get(__ret__, 'direct_connection_info'),
        display_name=pulumi.get(__ret__, 'display_name'),
        download_uri=pulumi.get(__ret__, 'download_uri'),
        is_locked=pulumi.get(__ret__, 'is_locked'),
        last_modified_by_api_key_id=pulumi.get(__ret__, 'last_modified_by_api_key_id'),
        last_modified_by_automation_id=pulumi.get(__ret__, 'last_modified_by_automation_id'),
        last_modified_by_bundle_registration_id=pulumi.get(__ret__, 'last_modified_by_bundle_registration_id'),
        last_modified_by_id=pulumi.get(__ret__, 'last_modified_by_id'),
        last_modified_by_remote_server_id=pulumi.get(__ret__, 'last_modified_by_remote_server_id'),
        last_modified_by_sync_id=pulumi.get(__ret__, 'last_modified_by_sync_id'),
        md5=pulumi.get(__ret__, 'md5'),
        mime_type=pulumi.get(__ret__, 'mime_type'),
        mtime=pulumi.get(__ret__, 'mtime'),
        path=pulumi.get(__ret__, 'path'),
        permissions=pulumi.get(__ret__, 'permissions'),
        preview=pulumi.get(__ret__, 'preview'),
        preview_id=pulumi.get(__ret__, 'preview_id'),
        priority_color=pulumi.get(__ret__, 'priority_color'),
        provided_mtime=pulumi.get(__ret__, 'provided_mtime'),
        region=pulumi.get(__ret__, 'region'),
        sha1=pulumi.get(__ret__, 'sha1'),
        sha256=pulumi.get(__ret__, 'sha256'),
        size=pulumi.get(__ret__, 'size'),
        subfolders_locked=pulumi.get(__ret__, 'subfolders_locked'),
        type=pulumi.get(__ret__, 'type'))
def get_folder_output(path: pulumi.Input[Optional[_builtins.str]] = None,
                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetFolderResult]:
    """
    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_filescom as filescom

    example_folder = filescom.get_folder(path="path")
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.str path: File/Folder path. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.
    """
    __args__ = dict()
    __args__['path'] = path
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('filescom:index/getFolder:getFolder', __args__, opts=opts, typ=GetFolderResult)
    return __ret__.apply(lambda __response__: GetFolderResult(
        crc32=pulumi.get(__response__, 'crc32'),
        created_at=pulumi.get(__response__, 'created_at'),
        created_by_api_key_id=pulumi.get(__response__, 'created_by_api_key_id'),
        created_by_as2_incoming_message_id=pulumi.get(__response__, 'created_by_as2_incoming_message_id'),
        created_by_automation_id=pulumi.get(__response__, 'created_by_automation_id'),
        created_by_bundle_registration_id=pulumi.get(__response__, 'created_by_bundle_registration_id'),
        created_by_id=pulumi.get(__response__, 'created_by_id'),
        created_by_inbox_id=pulumi.get(__response__, 'created_by_inbox_id'),
        created_by_remote_server_id=pulumi.get(__response__, 'created_by_remote_server_id'),
        created_by_sync_id=pulumi.get(__response__, 'created_by_sync_id'),
        custom_metadata=pulumi.get(__response__, 'custom_metadata'),
        direct_connection_info=pulumi.get(__response__, 'direct_connection_info'),
        display_name=pulumi.get(__response__, 'display_name'),
        download_uri=pulumi.get(__response__, 'download_uri'),
        is_locked=pulumi.get(__response__, 'is_locked'),
        last_modified_by_api_key_id=pulumi.get(__response__, 'last_modified_by_api_key_id'),
        last_modified_by_automation_id=pulumi.get(__response__, 'last_modified_by_automation_id'),
        last_modified_by_bundle_registration_id=pulumi.get(__response__, 'last_modified_by_bundle_registration_id'),
        last_modified_by_id=pulumi.get(__response__, 'last_modified_by_id'),
        last_modified_by_remote_server_id=pulumi.get(__response__, 'last_modified_by_remote_server_id'),
        last_modified_by_sync_id=pulumi.get(__response__, 'last_modified_by_sync_id'),
        md5=pulumi.get(__response__, 'md5'),
        mime_type=pulumi.get(__response__, 'mime_type'),
        mtime=pulumi.get(__response__, 'mtime'),
        path=pulumi.get(__response__, 'path'),
        permissions=pulumi.get(__response__, 'permissions'),
        preview=pulumi.get(__response__, 'preview'),
        preview_id=pulumi.get(__response__, 'preview_id'),
        priority_color=pulumi.get(__response__, 'priority_color'),
        provided_mtime=pulumi.get(__response__, 'provided_mtime'),
        region=pulumi.get(__response__, 'region'),
        sha1=pulumi.get(__response__, 'sha1'),
        sha256=pulumi.get(__response__, 'sha256'),
        size=pulumi.get(__response__, 'size'),
        subfolders_locked=pulumi.get(__response__, 'subfolders_locked'),
        type=pulumi.get(__response__, 'type')))
