// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Outputs
{

    [OutputType]
    public sealed class AutomationDefinitionNodeSwitchConfig
    {
        /// <summary>
        /// Switch cases. Each item contains a unique output name and the condition that sends items to it.
        /// </summary>
        public readonly ImmutableArray<Outputs.AutomationDefinitionNodeSwitchConfigCase> Cases;
        /// <summary>
        /// Error handlers. Each item selects an error pattern and whether to continue or propagate it.
        /// </summary>
        public readonly ImmutableArray<Outputs.AutomationDefinitionNodeSwitchConfigOnError> OnErrors;

        [OutputConstructor]
        private AutomationDefinitionNodeSwitchConfig(
            ImmutableArray<Outputs.AutomationDefinitionNodeSwitchConfigCase> cases,

            ImmutableArray<Outputs.AutomationDefinitionNodeSwitchConfigOnError> onErrors)
        {
            Cases = cases;
            OnErrors = onErrors;
        }
    }
}
