// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Outputs
{

    [OutputType]
    public sealed class AutomationDefinitionNodeAggregate
    {
        /// <summary>
        /// Configuration fields for this node type.
        /// </summary>
        public readonly Outputs.AutomationDefinitionNodeAggregateConfig? Config;
        /// <summary>
        /// Unique node ID within the graph.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Whether this node's output is included in the Automation result.
        /// </summary>
        public readonly bool? Return;

        [OutputConstructor]
        private AutomationDefinitionNodeAggregate(
            Outputs.AutomationDefinitionNodeAggregateConfig? config,

            string id,

            bool? @return)
        {
            Config = config;
            Id = id;
            Return = @return;
        }
    }
}
