// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Outputs
{

    [OutputType]
    public sealed class GetAutomationDefinitionNodeSendEmailConfigResult
    {
        public readonly ImmutableArray<string> Attachments;
        public readonly ImmutableArray<string> Bccs;
        /// <summary>
        /// A string value. Supports {{ fts }} interpolation, evaluated per item at execution time.
        /// </summary>
        public readonly string Body;
        public readonly ImmutableArray<string> Ccs;
        /// <summary>
        /// A string value. Supports {{ fts }} interpolation, evaluated per item at execution time.
        /// </summary>
        public readonly string From;
        /// <summary>
        /// Error handlers. Each item selects an error pattern and whether to continue or propagate it.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAutomationDefinitionNodeSendEmailConfigOnErrorResult> OnErrors;
        /// <summary>
        /// A string value. Supports {{ fts }} interpolation, evaluated per item at execution time.
        /// </summary>
        public readonly string Subject;
        public readonly ImmutableArray<string> Tos;

        [OutputConstructor]
        private GetAutomationDefinitionNodeSendEmailConfigResult(
            ImmutableArray<string> attachments,

            ImmutableArray<string> bccs,

            string body,

            ImmutableArray<string> ccs,

            string from,

            ImmutableArray<Outputs.GetAutomationDefinitionNodeSendEmailConfigOnErrorResult> onErrors,

            string subject,

            ImmutableArray<string> tos)
        {
            Attachments = attachments;
            Bccs = bccs;
            Body = body;
            Ccs = ccs;
            From = from;
            OnErrors = onErrors;
            Subject = subject;
            Tos = tos;
        }
    }
}
