// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Outputs
{

    [OutputType]
    public sealed class HolidayCalendarDefinitionMonths
    {
        public readonly ImmutableArray<Outputs.HolidayCalendarDefinitionMonthsCalculatedRule> CalculatedRules;
        public readonly ImmutableArray<Outputs.HolidayCalendarDefinitionMonthsFixedRule> FixedRules;
        public readonly ImmutableArray<Outputs.HolidayCalendarDefinitionMonthsWeekdayRule> WeekdayRules;

        [OutputConstructor]
        private HolidayCalendarDefinitionMonths(
            ImmutableArray<Outputs.HolidayCalendarDefinitionMonthsCalculatedRule> calculatedRules,

            ImmutableArray<Outputs.HolidayCalendarDefinitionMonthsFixedRule> fixedRules,

            ImmutableArray<Outputs.HolidayCalendarDefinitionMonthsWeekdayRule> weekdayRules)
        {
            CalculatedRules = calculatedRules;
            FixedRules = fixedRules;
            WeekdayRules = weekdayRules;
        }
    }
}
