// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Inputs
{

    public sealed class AutomationDefinitionNodeFilterConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A bare Files TransformScript expression, no braces.
        /// </summary>
        [Input("condition", required: true)]
        public Input<string> Condition { get; set; } = null!;

        [Input("onErrors")]
        private InputList<Inputs.AutomationDefinitionNodeFilterConfigOnErrorArgs>? _onErrors;

        /// <summary>
        /// Error handlers. Each item selects an error pattern and whether to continue or propagate it.
        /// </summary>
        public InputList<Inputs.AutomationDefinitionNodeFilterConfigOnErrorArgs> OnErrors
        {
            get => _onErrors ?? (_onErrors = new InputList<Inputs.AutomationDefinitionNodeFilterConfigOnErrorArgs>());
            set => _onErrors = value;
        }

        public AutomationDefinitionNodeFilterConfigArgs()
        {
        }
        public static new AutomationDefinitionNodeFilterConfigArgs Empty => new AutomationDefinitionNodeFilterConfigArgs();
    }
}
