// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Inputs
{

    public sealed class AutomationDefinitionNodeSetMetadataConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("metadata", required: true)]
        private InputMap<string>? _metadata;
        public InputMap<string> Metadata
        {
            get => _metadata ?? (_metadata = new InputMap<string>());
            set => _metadata = value;
        }

        [Input("onErrors")]
        private InputList<Inputs.AutomationDefinitionNodeSetMetadataConfigOnErrorArgs>? _onErrors;

        /// <summary>
        /// Error handlers. Each item selects an error pattern and whether to continue or propagate it.
        /// </summary>
        public InputList<Inputs.AutomationDefinitionNodeSetMetadataConfigOnErrorArgs> OnErrors
        {
            get => _onErrors ?? (_onErrors = new InputList<Inputs.AutomationDefinitionNodeSetMetadataConfigOnErrorArgs>());
            set => _onErrors = value;
        }

        public AutomationDefinitionNodeSetMetadataConfigArgs()
        {
        }
        public static new AutomationDefinitionNodeSetMetadataConfigArgs Empty => new AutomationDefinitionNodeSetMetadataConfigArgs();
    }
}
