// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Inputs
{

    public sealed class AutomationDefinitionNodeExtractConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("contentMode")]
        public Input<string>? ContentMode { get; set; }

        [Input("includeContent")]
        public Input<bool>? IncludeContent { get; set; }

        [Input("includeMetadata")]
        public Input<bool>? IncludeMetadata { get; set; }

        [Input("maxChars")]
        public Input<int>? MaxChars { get; set; }

        [Input("maxPages")]
        public Input<int>? MaxPages { get; set; }

        [Input("onErrors")]
        private InputList<Inputs.AutomationDefinitionNodeExtractConfigOnErrorGetArgs>? _onErrors;

        /// <summary>
        /// Error handlers. Each item selects an error pattern and whether to continue or propagate it.
        /// </summary>
        public InputList<Inputs.AutomationDefinitionNodeExtractConfigOnErrorGetArgs> OnErrors
        {
            get => _onErrors ?? (_onErrors = new InputList<Inputs.AutomationDefinitionNodeExtractConfigOnErrorGetArgs>());
            set => _onErrors = value;
        }

        public AutomationDefinitionNodeExtractConfigGetArgs()
        {
        }
        public static new AutomationDefinitionNodeExtractConfigGetArgs Empty => new AutomationDefinitionNodeExtractConfigGetArgs();
    }
}
