// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Jschady.Filescom.Inputs
{

    public sealed class HolidayCalendarDefinitionMonthsCalculatedRuleYearRangesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required start and end years.
        /// </summary>
        [Input("between")]
        public Input<Inputs.HolidayCalendarDefinitionMonthsCalculatedRuleYearRangesBetweenArgs>? Between { get; set; }

        /// <summary>
        /// First year in which the rule applies.
        /// </summary>
        [Input("from")]
        public Input<int>? From { get; set; }

        [Input("limiteds")]
        private InputList<int>? _limiteds;

        /// <summary>
        /// Years in which the rule applies.
        /// </summary>
        public InputList<int> Limiteds
        {
            get => _limiteds ?? (_limiteds = new InputList<int>());
            set => _limiteds = value;
        }

        /// <summary>
        /// Last year in which the rule applies.
        /// </summary>
        [Input("until")]
        public Input<int>? Until { get; set; }

        public HolidayCalendarDefinitionMonthsCalculatedRuleYearRangesArgs()
        {
        }
        public static new HolidayCalendarDefinitionMonthsCalculatedRuleYearRangesArgs Empty => new HolidayCalendarDefinitionMonthsCalculatedRuleYearRangesArgs();
    }
}
