// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package filescom

import (
	"context"
	"reflect"

	"github.com/jschady/pulumi-filescom/sdk/go/filescom/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An ExternalEvent is a log that is sent to the cloud from a client application such as the Files.com CLI.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := filescom.GetExternalEvent(ctx, &filescom.GetExternalEventArgs{
//				Id: 1,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func GetExternalEvent(ctx *pulumi.Context, args *GetExternalEventArgs, opts ...pulumi.InvokeOption) (*GetExternalEventResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetExternalEventResult
	err := ctx.Invoke("filescom:index/getExternalEvent:getExternalEvent", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getExternalEvent.
type GetExternalEventArgs struct {
	// Event ID
	Id int `pulumi:"id"`
}

// A collection of values returned by getExternalEvent.
type GetExternalEventResult struct {
	// Event body
	Body string `pulumi:"body"`
	// Link to log file.
	BodyUrl string `pulumi:"bodyUrl"`
	// External event create date/time
	CreatedAt string `pulumi:"createdAt"`
	// Type of event being recorded.
	EventType string `pulumi:"eventType"`
	// Event ID
	Id int `pulumi:"id"`
	// Status of event.
	Status string `pulumi:"status"`
}

func GetExternalEventOutput(ctx *pulumi.Context, args GetExternalEventOutputArgs, opts ...pulumi.InvokeOption) GetExternalEventResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("filescom:index/getExternalEvent:getExternalEvent", args, GetExternalEventResultOutput{}, options).(GetExternalEventResultOutput)
}

// A collection of arguments for invoking getExternalEvent.
type GetExternalEventOutputArgs struct {
	// Event ID
	Id pulumi.IntInput `pulumi:"id"`
}

func (GetExternalEventOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetExternalEventArgs)(nil)).Elem()
}

// A collection of values returned by getExternalEvent.
type GetExternalEventResultOutput struct{ *pulumi.OutputState }

func (GetExternalEventResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetExternalEventResult)(nil)).Elem()
}

func (o GetExternalEventResultOutput) ToGetExternalEventResultOutput() GetExternalEventResultOutput {
	return o
}

func (o GetExternalEventResultOutput) ToGetExternalEventResultOutputWithContext(ctx context.Context) GetExternalEventResultOutput {
	return o
}

// Event body
func (o GetExternalEventResultOutput) Body() pulumi.StringOutput {
	return o.ApplyT(func(v GetExternalEventResult) string { return v.Body }).(pulumi.StringOutput)
}

// Link to log file.
func (o GetExternalEventResultOutput) BodyUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetExternalEventResult) string { return v.BodyUrl }).(pulumi.StringOutput)
}

// External event create date/time
func (o GetExternalEventResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetExternalEventResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Type of event being recorded.
func (o GetExternalEventResultOutput) EventType() pulumi.StringOutput {
	return o.ApplyT(func(v GetExternalEventResult) string { return v.EventType }).(pulumi.StringOutput)
}

// Event ID
func (o GetExternalEventResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetExternalEventResult) int { return v.Id }).(pulumi.IntOutput)
}

// Status of event.
func (o GetExternalEventResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetExternalEventResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetExternalEventResultOutput{})
}
