// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package filescom

import (
	"context"
	"reflect"

	"github.com/jschady/pulumi-filescom/sdk/go/filescom/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Permission object represents a grant of access permission on a specific Path to a User or Group.
//
// They can be optionally recursive or nonrecursive into the subfolders of that path.
//
// A Permission may be applied to a User *or* a Group, but not both at once.
//
// The following table sets forth the available Permission types:
//
// | Permission | Access Level Granted | Automatically Also Includes/Implies Permissions |
//
// | --- | ----------- | --------------------- |
//
// | <span pulumi-lang-nodejs="`admin`" pulumi-lang-dotnet="`Admin`" pulumi-lang-go="`admin`" pulumi-lang-python="`admin`" pulumi-lang-yaml="`admin`" pulumi-lang-java="`admin`" pulumi-lang-hcl="`admin`">`admin`</span> | Able to manage Folder Behaviors, Permissions, and Notifications for the folder. Also grants all other permissions. | <span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`">`bundle`</span>, <span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`">`full`</span>, <span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`">`writeonly`</span>, <span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`">`readonly`</span>, <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span>, <span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`">`history`</span> |
//
// | <span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`">`bundle`</span> | Able to share files and folders via a Bundle (share link). | <span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`">`readonly`</span>, <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span> |
//
// | <span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`">`full`</span> | Able to read, write, move, delete, and rename files and folders. Also grants the ability to overwrite files upon upload. | <span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`">`writeonly`</span>, <span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`">`readonly`</span>, <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span> |
//
// | <span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`">`history`</span> | Able to view the history of files and folders and to create email notifications for themselves. | <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span> |
//
// | <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span> | Able to list files and folders, but not download. | none |
//
// | <span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`">`readonly`</span> | Able to list, preview, and download files and folders. | <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span> |
//
// | <span pulumi-lang-nodejs="`readonlySiteAdmin`" pulumi-lang-dotnet="`ReadonlySiteAdmin`" pulumi-lang-go="`readonlySiteAdmin`" pulumi-lang-python="`readonly_site_admin`" pulumi-lang-yaml="`readonlySiteAdmin`" pulumi-lang-java="`readonlySiteAdmin`" pulumi-lang-hcl="`readonly_site_admin`">`readonlySiteAdmin`</span> | Able to behave as a read-only Site Admin on a given child site. Only applies to child sites. | <span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`">`readonly`</span>, <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span>, <span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`">`history`</span> |
//
// | <span pulumi-lang-nodejs="`siteAdmin`" pulumi-lang-dotnet="`SiteAdmin`" pulumi-lang-go="`siteAdmin`" pulumi-lang-python="`site_admin`" pulumi-lang-yaml="`siteAdmin`" pulumi-lang-java="`siteAdmin`" pulumi-lang-hcl="`site_admin`">`siteAdmin`</span> | Able to behave as a Site Admin on a given child site. Only applies to child sites. | <span pulumi-lang-nodejs="`bundle`" pulumi-lang-dotnet="`Bundle`" pulumi-lang-go="`bundle`" pulumi-lang-python="`bundle`" pulumi-lang-yaml="`bundle`" pulumi-lang-java="`bundle`" pulumi-lang-hcl="`bundle`">`bundle`</span>, <span pulumi-lang-nodejs="`full`" pulumi-lang-dotnet="`Full`" pulumi-lang-go="`full`" pulumi-lang-python="`full`" pulumi-lang-yaml="`full`" pulumi-lang-java="`full`" pulumi-lang-hcl="`full`">`full`</span>, <span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`">`writeonly`</span>, <span pulumi-lang-nodejs="`readonly`" pulumi-lang-dotnet="`Readonly`" pulumi-lang-go="`readonly`" pulumi-lang-python="`readonly`" pulumi-lang-yaml="`readonly`" pulumi-lang-java="`readonly`" pulumi-lang-hcl="`readonly`">`readonly`</span>, <span pulumi-lang-nodejs="`list`" pulumi-lang-dotnet="`List`" pulumi-lang-go="`list`" pulumi-lang-python="`list`" pulumi-lang-yaml="`list`" pulumi-lang-java="`list`" pulumi-lang-hcl="`list`">`list`</span>, <span pulumi-lang-nodejs="`history`" pulumi-lang-dotnet="`History`" pulumi-lang-go="`history`" pulumi-lang-python="`history`" pulumi-lang-yaml="`history`" pulumi-lang-java="`history`" pulumi-lang-hcl="`history`">`history`</span> |
//
// | <span pulumi-lang-nodejs="`writeonly`" pulumi-lang-dotnet="`Writeonly`" pulumi-lang-go="`writeonly`" pulumi-lang-python="`writeonly`" pulumi-lang-yaml="`writeonly`" pulumi-lang-java="`writeonly`" pulumi-lang-hcl="`writeonly`">`writeonly`</span> | Able to upload files, create folders and list subfolders the user has write permission to. | none |
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/jschady/pulumi-filescom/sdk/go/filescom"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := filescom.GetPermission(ctx, &filescom.LookupPermissionArgs{
//				Id: 1,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupPermission(ctx *pulumi.Context, args *LookupPermissionArgs, opts ...pulumi.InvokeOption) (*LookupPermissionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupPermissionResult
	err := ctx.Invoke("filescom:index/getPermission:getPermission", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPermission.
type LookupPermissionArgs struct {
	// Permission ID
	Id int `pulumi:"id"`
}

// A collection of values returned by getPermission.
type LookupPermissionResult struct {
	// Group ID
	GroupId int `pulumi:"groupId"`
	// Group IDs when this permission requires multiple groups
	GroupIds []int `pulumi:"groupIds"`
	// Group name (if applicable)
	GroupName string `pulumi:"groupName"`
	// Group names when this permission requires multiple groups
	GroupNames []string `pulumi:"groupNames"`
	// Permission ID
	Id int `pulumi:"id"`
	// Partner ID (if applicable)
	PartnerId int `pulumi:"partnerId"`
	// Partner name (if applicable)
	PartnerName string `pulumi:"partnerName"`
	// Path. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.
	Path string `pulumi:"path"`
	// Permission type.  See the table referenced in the documentation for an explanation of each permission.
	Permission string `pulumi:"permission"`
	// Recursive: does this permission apply to subfolders?
	Recursive bool `pulumi:"recursive"`
	// Site ID
	SiteId int `pulumi:"siteId"`
	// User ID
	UserId int `pulumi:"userId"`
	// Username (if applicable)
	Username string `pulumi:"username"`
}

func LookupPermissionOutput(ctx *pulumi.Context, args LookupPermissionOutputArgs, opts ...pulumi.InvokeOption) LookupPermissionResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("filescom:index/getPermission:getPermission", args, LookupPermissionResultOutput{}, options).(LookupPermissionResultOutput)
}

// A collection of arguments for invoking getPermission.
type LookupPermissionOutputArgs struct {
	// Permission ID
	Id pulumi.IntInput `pulumi:"id"`
}

func (LookupPermissionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPermissionArgs)(nil)).Elem()
}

// A collection of values returned by getPermission.
type LookupPermissionResultOutput struct{ *pulumi.OutputState }

func (LookupPermissionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPermissionResult)(nil)).Elem()
}

func (o LookupPermissionResultOutput) ToLookupPermissionResultOutput() LookupPermissionResultOutput {
	return o
}

func (o LookupPermissionResultOutput) ToLookupPermissionResultOutputWithContext(ctx context.Context) LookupPermissionResultOutput {
	return o
}

// Group ID
func (o LookupPermissionResultOutput) GroupId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPermissionResult) int { return v.GroupId }).(pulumi.IntOutput)
}

// Group IDs when this permission requires multiple groups
func (o LookupPermissionResultOutput) GroupIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupPermissionResult) []int { return v.GroupIds }).(pulumi.IntArrayOutput)
}

// Group name (if applicable)
func (o LookupPermissionResultOutput) GroupName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.GroupName }).(pulumi.StringOutput)
}

// Group names when this permission requires multiple groups
func (o LookupPermissionResultOutput) GroupNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupPermissionResult) []string { return v.GroupNames }).(pulumi.StringArrayOutput)
}

// Permission ID
func (o LookupPermissionResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPermissionResult) int { return v.Id }).(pulumi.IntOutput)
}

// Partner ID (if applicable)
func (o LookupPermissionResultOutput) PartnerId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPermissionResult) int { return v.PartnerId }).(pulumi.IntOutput)
}

// Partner name (if applicable)
func (o LookupPermissionResultOutput) PartnerName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.PartnerName }).(pulumi.StringOutput)
}

// Path. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.
func (o LookupPermissionResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.Path }).(pulumi.StringOutput)
}

// Permission type.  See the table referenced in the documentation for an explanation of each permission.
func (o LookupPermissionResultOutput) Permission() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.Permission }).(pulumi.StringOutput)
}

// Recursive: does this permission apply to subfolders?
func (o LookupPermissionResultOutput) Recursive() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupPermissionResult) bool { return v.Recursive }).(pulumi.BoolOutput)
}

// Site ID
func (o LookupPermissionResultOutput) SiteId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPermissionResult) int { return v.SiteId }).(pulumi.IntOutput)
}

// User ID
func (o LookupPermissionResultOutput) UserId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPermissionResult) int { return v.UserId }).(pulumi.IntOutput)
}

// Username (if applicable)
func (o LookupPermissionResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPermissionResult) string { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPermissionResultOutput{})
}
