// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Clickwrap is a legal agreement (such as an NDA or Terms of Use) that your Users and/or Bundle/Inbox participants will need to agree to via a "Clickwrap" UI before accessing the site, bundle, or inbox.
 *
 * The values for <span pulumi-lang-nodejs="`useWithUsers`" pulumi-lang-dotnet="`UseWithUsers`" pulumi-lang-go="`useWithUsers`" pulumi-lang-python="`use_with_users`" pulumi-lang-yaml="`useWithUsers`" pulumi-lang-java="`useWithUsers`" pulumi-lang-hcl="`use_with_users`">`useWithUsers`</span>, <span pulumi-lang-nodejs="`useWithBundles`" pulumi-lang-dotnet="`UseWithBundles`" pulumi-lang-go="`useWithBundles`" pulumi-lang-python="`use_with_bundles`" pulumi-lang-yaml="`useWithBundles`" pulumi-lang-java="`useWithBundles`" pulumi-lang-hcl="`use_with_bundles`">`useWithBundles`</span>, <span pulumi-lang-nodejs="`useWithInboxes`" pulumi-lang-dotnet="`UseWithInboxes`" pulumi-lang-go="`useWithInboxes`" pulumi-lang-python="`use_with_inboxes`" pulumi-lang-yaml="`useWithInboxes`" pulumi-lang-java="`useWithInboxes`" pulumi-lang-hcl="`use_with_inboxes`">`useWithInboxes`</span> are explained as follows:
 *
 * * <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span> - This Clickwrap may not be used in this context.
 *
 * * <span pulumi-lang-nodejs="`availableToAllUsers`" pulumi-lang-dotnet="`AvailableToAllUsers`" pulumi-lang-go="`availableToAllUsers`" pulumi-lang-python="`available_to_all_users`" pulumi-lang-yaml="`availableToAllUsers`" pulumi-lang-java="`availableToAllUsers`" pulumi-lang-hcl="`available_to_all_users`">`availableToAllUsers`</span> - This Clickwrap may be assigned in this context by any user.
 *
 * * <span pulumi-lang-nodejs="`available`" pulumi-lang-dotnet="`Available`" pulumi-lang-go="`available`" pulumi-lang-python="`available`" pulumi-lang-yaml="`available`" pulumi-lang-java="`available`" pulumi-lang-hcl="`available`">`available`</span> - This Clickwrap may be assigned in this context, but only by Site Admins. We recognize that the name of this setting is somewhat ambiguous, but we maintain it for legacy reasons.
 *
 * * <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span> - This Clickwrap will always be used in this context, and may not be overridden.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleClickwrap = new filescom.Clickwrap("example_clickwrap", {
 *     name: "Example Site NDA for Files.com Use",
 *     body: "[Legal body text]",
 *     useWithBundles: "example",
 *     useWithInboxes: "example",
 *     useWithUsers: "example",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Clickwraps can be imported by specifying the id.
 *
 * ```sh
 * $ pulumi import filescom:index/clickwrap:Clickwrap example_clickwrap 1
 * ```
 */
export class Clickwrap extends pulumi.CustomResource {
    /**
     * Get an existing Clickwrap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClickwrapState, opts?: pulumi.CustomResourceOptions): Clickwrap {
        return new Clickwrap(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'filescom:index/clickwrap:Clickwrap';

    /**
     * Returns true if the given object is an instance of Clickwrap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Clickwrap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Clickwrap.__pulumiType;
    }

    /**
     * Body text of Clickwrap (supports Markdown formatting).
     */
    declare public readonly body: pulumi.Output<string>;
    /**
     * Name of the Clickwrap agreement (used when selecting from multiple Clickwrap agreements.)
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Use this Clickwrap for Bundles?
     */
    declare public readonly useWithBundles: pulumi.Output<string>;
    /**
     * Use this Clickwrap for Inboxes?
     */
    declare public readonly useWithInboxes: pulumi.Output<string>;
    /**
     * Use this Clickwrap for Users?  Values: <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`require`" pulumi-lang-dotnet="`Require`" pulumi-lang-go="`require`" pulumi-lang-python="`require`" pulumi-lang-yaml="`require`" pulumi-lang-java="`require`" pulumi-lang-hcl="`require`">`require`</span> (new user signup via email invitation only), <span pulumi-lang-nodejs="`requireAllUsersOnce`" pulumi-lang-dotnet="`RequireAllUsersOnce`" pulumi-lang-go="`requireAllUsersOnce`" pulumi-lang-python="`require_all_users_once`" pulumi-lang-yaml="`requireAllUsersOnce`" pulumi-lang-java="`requireAllUsersOnce`" pulumi-lang-hcl="`require_all_users_once`">`requireAllUsersOnce`</span> (show to all users at their next web login; once accepted, not shown again), <span pulumi-lang-nodejs="`requireAllUsersAlways`" pulumi-lang-dotnet="`RequireAllUsersAlways`" pulumi-lang-go="`requireAllUsersAlways`" pulumi-lang-python="`require_all_users_always`" pulumi-lang-yaml="`requireAllUsersAlways`" pulumi-lang-java="`requireAllUsersAlways`" pulumi-lang-hcl="`require_all_users_always`">`requireAllUsersAlways`</span> (show to all users on every web login).
     */
    declare public readonly useWithUsers: pulumi.Output<string>;

    /**
     * Create a Clickwrap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClickwrapArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClickwrapArgs | ClickwrapState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClickwrapState | undefined;
            resourceInputs["body"] = state?.body;
            resourceInputs["name"] = state?.name;
            resourceInputs["useWithBundles"] = state?.useWithBundles;
            resourceInputs["useWithInboxes"] = state?.useWithInboxes;
            resourceInputs["useWithUsers"] = state?.useWithUsers;
        } else {
            const args = argsOrState as ClickwrapArgs | undefined;
            resourceInputs["body"] = args?.body;
            resourceInputs["name"] = args?.name;
            resourceInputs["useWithBundles"] = args?.useWithBundles;
            resourceInputs["useWithInboxes"] = args?.useWithInboxes;
            resourceInputs["useWithUsers"] = args?.useWithUsers;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Clickwrap.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Clickwrap resources.
 */
export interface ClickwrapState {
    /**
     * Body text of Clickwrap (supports Markdown formatting).
     */
    body?: pulumi.Input<string | undefined>;
    /**
     * Name of the Clickwrap agreement (used when selecting from multiple Clickwrap agreements.)
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Use this Clickwrap for Bundles?
     */
    useWithBundles?: pulumi.Input<string | undefined>;
    /**
     * Use this Clickwrap for Inboxes?
     */
    useWithInboxes?: pulumi.Input<string | undefined>;
    /**
     * Use this Clickwrap for Users?  Values: <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`require`" pulumi-lang-dotnet="`Require`" pulumi-lang-go="`require`" pulumi-lang-python="`require`" pulumi-lang-yaml="`require`" pulumi-lang-java="`require`" pulumi-lang-hcl="`require`">`require`</span> (new user signup via email invitation only), <span pulumi-lang-nodejs="`requireAllUsersOnce`" pulumi-lang-dotnet="`RequireAllUsersOnce`" pulumi-lang-go="`requireAllUsersOnce`" pulumi-lang-python="`require_all_users_once`" pulumi-lang-yaml="`requireAllUsersOnce`" pulumi-lang-java="`requireAllUsersOnce`" pulumi-lang-hcl="`require_all_users_once`">`requireAllUsersOnce`</span> (show to all users at their next web login; once accepted, not shown again), <span pulumi-lang-nodejs="`requireAllUsersAlways`" pulumi-lang-dotnet="`RequireAllUsersAlways`" pulumi-lang-go="`requireAllUsersAlways`" pulumi-lang-python="`require_all_users_always`" pulumi-lang-yaml="`requireAllUsersAlways`" pulumi-lang-java="`requireAllUsersAlways`" pulumi-lang-hcl="`require_all_users_always`">`requireAllUsersAlways`</span> (show to all users on every web login).
     */
    useWithUsers?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Clickwrap resource.
 */
export interface ClickwrapArgs {
    /**
     * Body text of Clickwrap (supports Markdown formatting).
     */
    body?: pulumi.Input<string | undefined>;
    /**
     * Name of the Clickwrap agreement (used when selecting from multiple Clickwrap agreements.)
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Use this Clickwrap for Bundles?
     */
    useWithBundles?: pulumi.Input<string | undefined>;
    /**
     * Use this Clickwrap for Inboxes?
     */
    useWithInboxes?: pulumi.Input<string | undefined>;
    /**
     * Use this Clickwrap for Users?  Values: <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`require`" pulumi-lang-dotnet="`Require`" pulumi-lang-go="`require`" pulumi-lang-python="`require`" pulumi-lang-yaml="`require`" pulumi-lang-java="`require`" pulumi-lang-hcl="`require`">`require`</span> (new user signup via email invitation only), <span pulumi-lang-nodejs="`requireAllUsersOnce`" pulumi-lang-dotnet="`RequireAllUsersOnce`" pulumi-lang-go="`requireAllUsersOnce`" pulumi-lang-python="`require_all_users_once`" pulumi-lang-yaml="`requireAllUsersOnce`" pulumi-lang-java="`requireAllUsersOnce`" pulumi-lang-hcl="`require_all_users_once`">`requireAllUsersOnce`</span> (show to all users at their next web login; once accepted, not shown again), <span pulumi-lang-nodejs="`requireAllUsersAlways`" pulumi-lang-dotnet="`RequireAllUsersAlways`" pulumi-lang-go="`requireAllUsersAlways`" pulumi-lang-python="`require_all_users_always`" pulumi-lang-yaml="`requireAllUsersAlways`" pulumi-lang-java="`requireAllUsersAlways`" pulumi-lang-hcl="`require_all_users_always`">`requireAllUsersAlways`</span> (show to all users on every web login).
     */
    useWithUsers?: pulumi.Input<string | undefined>;
}
