// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Clickwrap is a legal agreement (such as an NDA or Terms of Use) that your Users and/or Bundle/Inbox participants will need to agree to via a "Clickwrap" UI before accessing the site, bundle, or inbox.
 *
 * The values for <span pulumi-lang-nodejs="`useWithUsers`" pulumi-lang-dotnet="`UseWithUsers`" pulumi-lang-go="`useWithUsers`" pulumi-lang-python="`use_with_users`" pulumi-lang-yaml="`useWithUsers`" pulumi-lang-java="`useWithUsers`" pulumi-lang-hcl="`use_with_users`">`useWithUsers`</span>, <span pulumi-lang-nodejs="`useWithBundles`" pulumi-lang-dotnet="`UseWithBundles`" pulumi-lang-go="`useWithBundles`" pulumi-lang-python="`use_with_bundles`" pulumi-lang-yaml="`useWithBundles`" pulumi-lang-java="`useWithBundles`" pulumi-lang-hcl="`use_with_bundles`">`useWithBundles`</span>, <span pulumi-lang-nodejs="`useWithInboxes`" pulumi-lang-dotnet="`UseWithInboxes`" pulumi-lang-go="`useWithInboxes`" pulumi-lang-python="`use_with_inboxes`" pulumi-lang-yaml="`useWithInboxes`" pulumi-lang-java="`useWithInboxes`" pulumi-lang-hcl="`use_with_inboxes`">`useWithInboxes`</span> are explained as follows:
 *
 * * <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span> - This Clickwrap may not be used in this context.
 *
 * * <span pulumi-lang-nodejs="`availableToAllUsers`" pulumi-lang-dotnet="`AvailableToAllUsers`" pulumi-lang-go="`availableToAllUsers`" pulumi-lang-python="`available_to_all_users`" pulumi-lang-yaml="`availableToAllUsers`" pulumi-lang-java="`availableToAllUsers`" pulumi-lang-hcl="`available_to_all_users`">`availableToAllUsers`</span> - This Clickwrap may be assigned in this context by any user.
 *
 * * <span pulumi-lang-nodejs="`available`" pulumi-lang-dotnet="`Available`" pulumi-lang-go="`available`" pulumi-lang-python="`available`" pulumi-lang-yaml="`available`" pulumi-lang-java="`available`" pulumi-lang-hcl="`available`">`available`</span> - This Clickwrap may be assigned in this context, but only by Site Admins. We recognize that the name of this setting is somewhat ambiguous, but we maintain it for legacy reasons.
 *
 * * <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span> - This Clickwrap will always be used in this context, and may not be overridden.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleClickwrap = filescom.getClickwrap({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getClickwrap(args: GetClickwrapArgs, opts?: pulumi.InvokeOptions): Promise<GetClickwrapResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("filescom:index/getClickwrap:getClickwrap", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getClickwrap.
 */
export interface GetClickwrapArgs {
    /**
     * Clickwrap ID
     */
    id: number;
}

/**
 * A collection of values returned by getClickwrap.
 */
export interface GetClickwrapResult {
    /**
     * Body text of Clickwrap (supports Markdown formatting).
     */
    readonly body: string;
    /**
     * Clickwrap ID
     */
    readonly id: number;
    /**
     * Name of the Clickwrap agreement (used when selecting from multiple Clickwrap agreements.)
     */
    readonly name: string;
    /**
     * Use this Clickwrap for Bundles?
     */
    readonly useWithBundles: string;
    /**
     * Use this Clickwrap for Inboxes?
     */
    readonly useWithInboxes: string;
    /**
     * Use this Clickwrap for Users?  Values: <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`require`" pulumi-lang-dotnet="`Require`" pulumi-lang-go="`require`" pulumi-lang-python="`require`" pulumi-lang-yaml="`require`" pulumi-lang-java="`require`" pulumi-lang-hcl="`require`">`require`</span> (new user signup via email invitation only), <span pulumi-lang-nodejs="`requireAllUsersOnce`" pulumi-lang-dotnet="`RequireAllUsersOnce`" pulumi-lang-go="`requireAllUsersOnce`" pulumi-lang-python="`require_all_users_once`" pulumi-lang-yaml="`requireAllUsersOnce`" pulumi-lang-java="`requireAllUsersOnce`" pulumi-lang-hcl="`require_all_users_once`">`requireAllUsersOnce`</span> (show to all users at their next web login; once accepted, not shown again), <span pulumi-lang-nodejs="`requireAllUsersAlways`" pulumi-lang-dotnet="`RequireAllUsersAlways`" pulumi-lang-go="`requireAllUsersAlways`" pulumi-lang-python="`require_all_users_always`" pulumi-lang-yaml="`requireAllUsersAlways`" pulumi-lang-java="`requireAllUsersAlways`" pulumi-lang-hcl="`require_all_users_always`">`requireAllUsersAlways`</span> (show to all users on every web login).
     */
    readonly useWithUsers: string;
}
/**
 * A Clickwrap is a legal agreement (such as an NDA or Terms of Use) that your Users and/or Bundle/Inbox participants will need to agree to via a "Clickwrap" UI before accessing the site, bundle, or inbox.
 *
 * The values for <span pulumi-lang-nodejs="`useWithUsers`" pulumi-lang-dotnet="`UseWithUsers`" pulumi-lang-go="`useWithUsers`" pulumi-lang-python="`use_with_users`" pulumi-lang-yaml="`useWithUsers`" pulumi-lang-java="`useWithUsers`" pulumi-lang-hcl="`use_with_users`">`useWithUsers`</span>, <span pulumi-lang-nodejs="`useWithBundles`" pulumi-lang-dotnet="`UseWithBundles`" pulumi-lang-go="`useWithBundles`" pulumi-lang-python="`use_with_bundles`" pulumi-lang-yaml="`useWithBundles`" pulumi-lang-java="`useWithBundles`" pulumi-lang-hcl="`use_with_bundles`">`useWithBundles`</span>, <span pulumi-lang-nodejs="`useWithInboxes`" pulumi-lang-dotnet="`UseWithInboxes`" pulumi-lang-go="`useWithInboxes`" pulumi-lang-python="`use_with_inboxes`" pulumi-lang-yaml="`useWithInboxes`" pulumi-lang-java="`useWithInboxes`" pulumi-lang-hcl="`use_with_inboxes`">`useWithInboxes`</span> are explained as follows:
 *
 * * <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span> - This Clickwrap may not be used in this context.
 *
 * * <span pulumi-lang-nodejs="`availableToAllUsers`" pulumi-lang-dotnet="`AvailableToAllUsers`" pulumi-lang-go="`availableToAllUsers`" pulumi-lang-python="`available_to_all_users`" pulumi-lang-yaml="`availableToAllUsers`" pulumi-lang-java="`availableToAllUsers`" pulumi-lang-hcl="`available_to_all_users`">`availableToAllUsers`</span> - This Clickwrap may be assigned in this context by any user.
 *
 * * <span pulumi-lang-nodejs="`available`" pulumi-lang-dotnet="`Available`" pulumi-lang-go="`available`" pulumi-lang-python="`available`" pulumi-lang-yaml="`available`" pulumi-lang-java="`available`" pulumi-lang-hcl="`available`">`available`</span> - This Clickwrap may be assigned in this context, but only by Site Admins. We recognize that the name of this setting is somewhat ambiguous, but we maintain it for legacy reasons.
 *
 * * <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span> - This Clickwrap will always be used in this context, and may not be overridden.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleClickwrap = filescom.getClickwrap({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getClickwrapOutput(args: GetClickwrapOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClickwrapResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("filescom:index/getClickwrap:getClickwrap", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getClickwrap.
 */
export interface GetClickwrapOutputArgs {
    /**
     * Clickwrap ID
     */
    id: pulumi.Input<number>;
}
