// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An EventDeliveryAttempt records delivery state for an EventRecord and EventTarget.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleEventDeliveryAttempt = filescom.getEventDeliveryAttempt({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getEventDeliveryAttempt(args: GetEventDeliveryAttemptArgs, opts?: pulumi.InvokeOptions): Promise<GetEventDeliveryAttemptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("filescom:index/getEventDeliveryAttempt:getEventDeliveryAttempt", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getEventDeliveryAttempt.
 */
export interface GetEventDeliveryAttemptArgs {
    /**
     * Event Delivery Attempt ID
     */
    id: number;
}

/**
 * A collection of values returned by getEventDeliveryAttempt.
 */
export interface GetEventDeliveryAttemptResult {
    /**
     * Number of delivery attempts made.
     */
    readonly attemptNumber: number;
    /**
     * Delivery Attempt create date/time.
     */
    readonly createdAt: string;
    /**
     * Successful delivery date/time.
     */
    readonly deliveredAt: string;
    /**
     * Delivery error message, if applicable.
     */
    readonly errorMessage: string;
    /**
     * Event Record ID
     */
    readonly eventRecordId: number;
    /**
     * Event Subscription ID
     */
    readonly eventSubscriptionId: number;
    /**
     * Event Target ID
     */
    readonly eventTargetId: number;
    /**
     * Event Delivery Attempt ID
     */
    readonly id: number;
    /**
     * Most recent attempt date/time.
     */
    readonly lastAttemptedAt: string;
    /**
     * Delivery latency in milliseconds.
     */
    readonly latencyMs: number;
    /**
     * Next scheduled attempt date/time.
     */
    readonly nextAttemptAt: string;
    /**
     * Delivery response body, if applicable.
     */
    readonly responseBody: string;
    /**
     * HTTP response code, if applicable.
     */
    readonly responseCode: number;
    /**
     * Delivery status.
     */
    readonly status: string;
    /**
     * Workspace ID. 0 means the default workspace or site-wide.
     */
    readonly workspaceId: number;
}
/**
 * An EventDeliveryAttempt records delivery state for an EventRecord and EventTarget.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleEventDeliveryAttempt = filescom.getEventDeliveryAttempt({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getEventDeliveryAttemptOutput(args: GetEventDeliveryAttemptOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEventDeliveryAttemptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("filescom:index/getEventDeliveryAttempt:getEventDeliveryAttempt", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getEventDeliveryAttempt.
 */
export interface GetEventDeliveryAttemptOutputArgs {
    /**
     * Event Delivery Attempt ID
     */
    id: pulumi.Input<number>;
}
