// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A PendingWorkEvent is a log record for pending file work failures, such as GPG Encryption and GPG Decryption.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const examplePendingWorkEvent = filescom.getPendingWorkEvent({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getPendingWorkEvent(args: GetPendingWorkEventArgs, opts?: pulumi.InvokeOptions): Promise<GetPendingWorkEventResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("filescom:index/getPendingWorkEvent:getPendingWorkEvent", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getPendingWorkEvent.
 */
export interface GetPendingWorkEventArgs {
    /**
     * Event ID
     */
    id: number;
}

/**
 * A collection of values returned by getPendingWorkEvent.
 */
export interface GetPendingWorkEventResult {
    /**
     * Event body.
     */
    readonly body: string;
    /**
     * Link to log file.
     */
    readonly bodyUrl: string;
    /**
     * Event create date/time.
     */
    readonly createdAt: string;
    /**
     * Event errors.
     */
    readonly eventErrors: string[];
    /**
     * Type of pending work event being recorded.
     */
    readonly eventType: string;
    /**
     * Folder Behavior ID.
     */
    readonly folderBehaviorId: number;
    /**
     * Event ID
     */
    readonly id: number;
    /**
     * Status of event.
     */
    readonly status: string;
}
/**
 * A PendingWorkEvent is a log record for pending file work failures, such as GPG Encryption and GPG Decryption.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const examplePendingWorkEvent = filescom.getPendingWorkEvent({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getPendingWorkEventOutput(args: GetPendingWorkEventOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPendingWorkEventResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("filescom:index/getPendingWorkEvent:getPendingWorkEvent", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getPendingWorkEvent.
 */
export interface GetPendingWorkEventOutputArgs {
    /**
     * Event ID
     */
    id: pulumi.Input<number>;
}
