// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleSiemHttpDestination = filescom.getSiemHttpDestination({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getSiemHttpDestination(args: GetSiemHttpDestinationArgs, opts?: pulumi.InvokeOptions): Promise<GetSiemHttpDestinationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("filescom:index/getSiemHttpDestination:getSiemHttpDestination", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getSiemHttpDestination.
 */
export interface GetSiemHttpDestinationArgs {
    /**
     * SIEM HTTP Destination ID
     */
    id: number;
}

/**
 * A collection of values returned by getSiemHttpDestination.
 */
export interface GetSiemHttpDestinationResult {
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly actionEntriesSent: number;
    /**
     * Whether or not sending is enabled for action logs.
     */
    readonly actionSendEnabled: boolean;
    /**
     * Additional HTTP Headers included in calls to the destination URL
     */
    readonly additionalHeaders: any;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly apiRequestEntriesSent: number;
    /**
     * Whether or not sending is enabled for<span pulumi-lang-nodejs=" apiRequest " pulumi-lang-dotnet=" ApiRequest " pulumi-lang-go=" apiRequest " pulumi-lang-python=" api_request " pulumi-lang-yaml=" apiRequest " pulumi-lang-java=" apiRequest " pulumi-lang-hcl=" api_request "> apiRequest </span>logs.
     */
    readonly apiRequestSendEnabled: boolean;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly automationEntriesSent: number;
    /**
     * Whether or not sending is enabled for automation logs.
     */
    readonly automationSendEnabled: boolean;
    /**
     * Applicable only for destination types: azure, azure_legacy. Immutable ID of the Data Collection Rule.
     */
    readonly azureDcrImmutableId: string;
    /**
     * Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Client ID.
     */
    readonly azureOauthClientCredentialsClientId: string;
    /**
     * Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Client Secret.
     */
    readonly azureOauthClientCredentialsClientSecretMasked: string;
    /**
     * Applicable only for destination types: azure, azure_legacy. Client Credentials OAuth Tenant ID.
     */
    readonly azureOauthClientCredentialsTenantId: string;
    /**
     * Applicable only for destination type: azure. Name of the stream in the DCR that represents the destination table.
     */
    readonly azureStreamName: string;
    /**
     * Connection Test Entry
     */
    readonly connectionTestEntry: string;
    /**
     * Applicable only for destination type: crowdstrike. Authentication token provided by Crowdstrike.
     */
    readonly crowdstrikeTokenMasked: string;
    /**
     * Applicable only for destination type: datadog. API key provided by Datadog.
     */
    readonly datadogApiKeyMasked: string;
    /**
     * Destination Type
     */
    readonly destinationType: string;
    /**
     * Destination Url
     */
    readonly destinationUrl: string;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly emailEntriesSent: number;
    /**
     * Whether or not sending is enabled for email logs.
     */
    readonly emailSendEnabled: boolean;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly exavaultApiRequestEntriesSent: number;
    /**
     * Whether or not sending is enabled for exavault*api*request logs.
     */
    readonly exavaultApiRequestSendEnabled: boolean;
    /**
     * Applicable only for destination type: file. Destination folder path on Files.com.
     */
    readonly fileDestinationPath: string;
    /**
     * Applicable only for destination type: file. Generated file format.
     */
    readonly fileFormat: string;
    /**
     * Applicable only for destination type: file. Interval, in minutes, between file deliveries.
     */
    readonly fileIntervalMinutes: number;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly ftpActionEntriesSent: number;
    /**
     * Whether or not sending is enabled for<span pulumi-lang-nodejs=" ftpAction " pulumi-lang-dotnet=" FtpAction " pulumi-lang-go=" ftpAction " pulumi-lang-python=" ftp_action " pulumi-lang-yaml=" ftpAction " pulumi-lang-java=" ftpAction " pulumi-lang-hcl=" ftp_action "> ftpAction </span>logs.
     */
    readonly ftpActionSendEnabled: boolean;
    /**
     * Applicable only for destination type: generic. Indicates the type of HTTP body. Can be json*newline or json*array. json*newline is multiple log entries as JSON separated by newlines. json*array is a single JSON array containing multiple log entries as JSON.
     */
    readonly genericPayloadType: string;
    /**
     * SIEM HTTP Destination ID
     */
    readonly id: number;
    /**
     * Duration of the last HTTP Call in milliseconds
     */
    readonly lastHttpCallDurationMs: number;
    /**
     * Last HTTP Call Error Message if applicable
     */
    readonly lastHttpCallErrorMessage: string;
    /**
     * Last HTTP Call Response Body. Large responses are truncated.
     */
    readonly lastHttpCallResponseBody: string;
    /**
     * Last HTTP Call Response Code
     */
    readonly lastHttpCallResponseCode: number;
    /**
     * Was the last HTTP call made successful?
     */
    readonly lastHttpCallSuccess: boolean;
    /**
     * Type of URL that was last called. Can be <span pulumi-lang-nodejs="`destinationUrl`" pulumi-lang-dotnet="`DestinationUrl`" pulumi-lang-go="`destinationUrl`" pulumi-lang-python="`destination_url`" pulumi-lang-yaml="`destinationUrl`" pulumi-lang-java="`destinationUrl`" pulumi-lang-hcl="`destination_url`">`destinationUrl`</span> or <span pulumi-lang-nodejs="`azureOauthClientCredentialsUrl`" pulumi-lang-dotnet="`AzureOauthClientCredentialsUrl`" pulumi-lang-go="`azureOauthClientCredentialsUrl`" pulumi-lang-python="`azure_oauth_client_credentials_url`" pulumi-lang-yaml="`azureOauthClientCredentialsUrl`" pulumi-lang-java="`azureOauthClientCredentialsUrl`" pulumi-lang-hcl="`azure_oauth_client_credentials_url`">`azureOauthClientCredentialsUrl`</span>
     */
    readonly lastHttpCallTargetType: string;
    /**
     * Time of Last HTTP Call
     */
    readonly lastHttpCallTime: string;
    /**
     * Time of Most Recent Successful HTTP Call
     */
    readonly mostRecentHttpCallSuccessTime: string;
    /**
     * Name for this Destination
     */
    readonly name: string;
    /**
     * Applicable only for destination type: new_relic. API key provided by New Relic.
     */
    readonly newRelicApiKeyMasked: string;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly outboundConnectionEntriesSent: number;
    /**
     * Whether or not sending is enabled for<span pulumi-lang-nodejs=" outboundConnection " pulumi-lang-dotnet=" OutboundConnection " pulumi-lang-go=" outboundConnection " pulumi-lang-python=" outbound_connection " pulumi-lang-yaml=" outboundConnection " pulumi-lang-java=" outboundConnection " pulumi-lang-hcl=" outbound_connection "> outboundConnection </span>logs.
     */
    readonly outboundConnectionSendEnabled: boolean;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly publicHostingRequestEntriesSent: number;
    /**
     * Whether or not sending is enabled for public*hosting*request logs.
     */
    readonly publicHostingRequestSendEnabled: boolean;
    /**
     * Applicable only for destination type: qradar. Basic auth password provided by QRadar.
     */
    readonly qradarPasswordMasked: string;
    /**
     * Applicable only for destination type: qradar. Basic auth username provided by QRadar.
     */
    readonly qradarUsername: string;
    /**
     * Whether this SIEM HTTP Destination is currently being sent to or not
     */
    readonly sendingActive: boolean;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly settingsChangeEntriesSent: number;
    /**
     * Whether or not sending is enabled for<span pulumi-lang-nodejs=" settingsChange " pulumi-lang-dotnet=" SettingsChange " pulumi-lang-go=" settingsChange " pulumi-lang-python=" settings_change " pulumi-lang-yaml=" settingsChange " pulumi-lang-java=" settingsChange " pulumi-lang-hcl=" settings_change "> settingsChange </span>logs.
     */
    readonly settingsChangeSendEnabled: boolean;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly sftpActionEntriesSent: number;
    /**
     * Whether or not sending is enabled for<span pulumi-lang-nodejs=" sftpAction " pulumi-lang-dotnet=" SftpAction " pulumi-lang-go=" sftpAction " pulumi-lang-python=" sftp_action " pulumi-lang-yaml=" sftpAction " pulumi-lang-java=" sftpAction " pulumi-lang-hcl=" sftp_action "> sftpAction </span>logs.
     */
    readonly sftpActionSendEnabled: boolean;
    /**
     * Applicable only for destination type: solar_winds. Authentication token provided by Solar Winds.
     */
    readonly solarWindsTokenMasked: string;
    /**
     * Applicable only for destination types: splunk, splunk_compatible. Authentication token for the destination.
     */
    readonly splunkTokenMasked: string;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly syncEntriesSent: number;
    /**
     * Whether or not sending is enabled for sync logs.
     */
    readonly syncSendEnabled: boolean;
    /**
     * Number of log entries sent for the lifetime of this destination.
     */
    readonly webDavActionEntriesSent: number;
    /**
     * Whether or not sending is enabled for web*dav*action logs.
     */
    readonly webDavActionSendEnabled: boolean;
}
/**
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleSiemHttpDestination = filescom.getSiemHttpDestination({
 *     id: 1,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getSiemHttpDestinationOutput(args: GetSiemHttpDestinationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSiemHttpDestinationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("filescom:index/getSiemHttpDestination:getSiemHttpDestination", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getSiemHttpDestination.
 */
export interface GetSiemHttpDestinationOutputArgs {
    /**
     * SIEM HTTP Destination ID
     */
    id: pulumi.Input<number>;
}
