// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Snapshots allow you to create a read-only archive of files at a specific point in time. You can define a snapshot, add files to it, and then finalize it. Once finalized, the snapshot’s contents are immutable.
 *
 * Each snapshot may have an expiration date. When the expiration date is reached, the snapshot is automatically deleted from the Files.com platform.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as filescom from "pulumi-filescom";
 *
 * const exampleSnapshot = new filescom.Snapshot("example_snapshot", {
 *     expiresAt: "2000-01-01T01:00:00Z",
 *     name: "My Snapshot",
 *     workspaceId: 0,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Snapshots can be imported by specifying the id.
 *
 * ```sh
 * $ pulumi import filescom:index/snapshot:Snapshot example_snapshot 1
 * ```
 */
export class Snapshot extends pulumi.CustomResource {
    /**
     * Get an existing Snapshot resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SnapshotState, opts?: pulumi.CustomResourceOptions): Snapshot {
        return new Snapshot(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'filescom:index/snapshot:Snapshot';

    /**
     * Returns true if the given object is an instance of Snapshot.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Snapshot {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Snapshot.__pulumiType;
    }

    /**
     * The bundle using this snapshot, if applicable.
     */
    declare public /*out*/ readonly bundleId: pulumi.Output<number>;
    /**
     * When the snapshot expires.
     */
    declare public readonly expiresAt: pulumi.Output<string>;
    /**
     * When the snapshot was finalized.
     */
    declare public /*out*/ readonly finalizedAt: pulumi.Output<string>;
    /**
     * A name for the snapshot.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * An array of paths to add to the snapshot.
     */
    declare public readonly paths: pulumi.Output<string[] | undefined>;
    /**
     * The user that created this snapshot, if applicable.
     */
    declare public /*out*/ readonly userId: pulumi.Output<number>;
    /**
     * Workspace ID. <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> means the default workspace.
     */
    declare public readonly workspaceId: pulumi.Output<number>;

    /**
     * Create a Snapshot resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SnapshotArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SnapshotArgs | SnapshotState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SnapshotState | undefined;
            resourceInputs["bundleId"] = state?.bundleId;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["finalizedAt"] = state?.finalizedAt;
            resourceInputs["name"] = state?.name;
            resourceInputs["paths"] = state?.paths;
            resourceInputs["userId"] = state?.userId;
            resourceInputs["workspaceId"] = state?.workspaceId;
        } else {
            const args = argsOrState as SnapshotArgs | undefined;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["name"] = args?.name;
            resourceInputs["paths"] = args?.paths ? pulumi.secret(args.paths) : undefined;
            resourceInputs["workspaceId"] = args?.workspaceId;
            resourceInputs["bundleId"] = undefined /*out*/;
            resourceInputs["finalizedAt"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["paths"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Snapshot.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Snapshot resources.
 */
export interface SnapshotState {
    /**
     * The bundle using this snapshot, if applicable.
     */
    bundleId?: pulumi.Input<number | undefined>;
    /**
     * When the snapshot expires.
     */
    expiresAt?: pulumi.Input<string | undefined>;
    /**
     * When the snapshot was finalized.
     */
    finalizedAt?: pulumi.Input<string | undefined>;
    /**
     * A name for the snapshot.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * An array of paths to add to the snapshot.
     */
    paths?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The user that created this snapshot, if applicable.
     */
    userId?: pulumi.Input<number | undefined>;
    /**
     * Workspace ID. <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> means the default workspace.
     */
    workspaceId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Snapshot resource.
 */
export interface SnapshotArgs {
    /**
     * When the snapshot expires.
     */
    expiresAt?: pulumi.Input<string | undefined>;
    /**
     * A name for the snapshot.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * An array of paths to add to the snapshot.
     */
    paths?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Workspace ID. <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> means the default workspace.
     */
    workspaceId?: pulumi.Input<number | undefined>;
}
